// Copyright (c) 2020 Arista Networks, Inc.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the COPYING file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: arista/subscriptions/subscriptions.proto

package subscriptions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_UNSPECIFIED Operation = 0
	// INITIAL indicates the associated notification is that of the
	// current state and a fully-specified Resource is provided.
	Operation_INITIAL Operation = 10
	// INITIAL_SYNC_COMPLETE indicates all existing-state has been
	// streamed to the client. This status will be sent in an
	// otherwise-empty message and no subsequent INITIAL messages
	// should be expected.
	Operation_INITIAL_SYNC_COMPLETE Operation = 11
	// UPDATED indicates the associated notification carries
	// modification to the last-streamed state. This indicates
	// the contained Resource may be a partial diff, though, it
	// may contain a fully-specified Resource.
	Operation_UPDATED Operation = 20
	// DETLETED indicates the associated notification carries
	// a deletion. The Resource's key will always be set in this case,
	// but no other fields should be expected.
	Operation_DELETED Operation = 30
	// PARTIAL_DELETE indicates the associated notification carries
	// deletions of specific fields within the last-streamed state.
	// The Resource's key is always set.
	//
	// Note:
	// Not used at the moment. Deletion of specific fields will
	// come with UPDATED operation.
	Operation_PARTIAL_DELETE Operation = 40
	// BATCH_START indicates the beginning of a batch of notifications.
	// This message will carry no resource value. A corresponding BATCH_END
	// message will mark the end of the batch. The semantics of what a
	// batch means is defined by the service.
	Operation_BATCH_START Operation = 50
	// BATCH_END indicates the end of a batch of notifications that
	// began with a BATCH_START message. This message will carry no
	// resource value.
	Operation_BATCH_END Operation = 51
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0:  "UNSPECIFIED",
		10: "INITIAL",
		11: "INITIAL_SYNC_COMPLETE",
		20: "UPDATED",
		30: "DELETED",
		40: "PARTIAL_DELETE",
		50: "BATCH_START",
		51: "BATCH_END",
	}
	Operation_value = map[string]int32{
		"UNSPECIFIED":           0,
		"INITIAL":               10,
		"INITIAL_SYNC_COMPLETE": 11,
		"UPDATED":               20,
		"DELETED":               30,
		"PARTIAL_DELETE":        40,
		"BATCH_START":           50,
		"BATCH_END":             51,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_arista_subscriptions_subscriptions_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_arista_subscriptions_subscriptions_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_arista_subscriptions_subscriptions_proto_rawDescGZIP(), []int{0}
}

var File_arista_subscriptions_subscriptions_proto protoreflect.FileDescriptor

const file_arista_subscriptions_subscriptions_proto_rawDesc = "" +
	"\n" +
	"(arista/subscriptions/subscriptions.proto\x12\x14arista.subscriptions*\x92\x01\n" +
	"\tOperation\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aINITIAL\x10\n" +
	"\x12\x19\n" +
	"\x15INITIAL_SYNC_COMPLETE\x10\v\x12\v\n" +
	"\aUPDATED\x10\x14\x12\v\n" +
	"\aDELETED\x10\x1e\x12\x12\n" +
	"\x0ePARTIAL_DELETE\x10(\x12\x0f\n" +
	"\vBATCH_START\x102\x12\r\n" +
	"\tBATCH_END\x103B\xeb\x01\n" +
	"\x18com.arista.subscriptionsB\x12SubscriptionsProtoP\x01ZJgithub.com/ioplane/terraform-provider-cvp/internal/pb/arista/subscriptions\xa2\x02\x03ASX\xaa\x02\x14Arista.Subscriptions\xca\x02\x14Arista\\Subscriptions\xe2\x02 Arista\\Subscriptions\\GPBMetadata\xea\x02\x15Arista::Subscriptionsb\x06proto3"

var (
	file_arista_subscriptions_subscriptions_proto_rawDescOnce sync.Once
	file_arista_subscriptions_subscriptions_proto_rawDescData []byte
)

func file_arista_subscriptions_subscriptions_proto_rawDescGZIP() []byte {
	file_arista_subscriptions_subscriptions_proto_rawDescOnce.Do(func() {
		file_arista_subscriptions_subscriptions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arista_subscriptions_subscriptions_proto_rawDesc), len(file_arista_subscriptions_subscriptions_proto_rawDesc)))
	})
	return file_arista_subscriptions_subscriptions_proto_rawDescData
}

var file_arista_subscriptions_subscriptions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_arista_subscriptions_subscriptions_proto_goTypes = []any{
	(Operation)(0), // 0: arista.subscriptions.Operation
}
var file_arista_subscriptions_subscriptions_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_arista_subscriptions_subscriptions_proto_init() }
func file_arista_subscriptions_subscriptions_proto_init() {
	if File_arista_subscriptions_subscriptions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arista_subscriptions_subscriptions_proto_rawDesc), len(file_arista_subscriptions_subscriptions_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_arista_subscriptions_subscriptions_proto_goTypes,
		DependencyIndexes: file_arista_subscriptions_subscriptions_proto_depIdxs,
		EnumInfos:         file_arista_subscriptions_subscriptions_proto_enumTypes,
	}.Build()
	File_arista_subscriptions_subscriptions_proto = out.File
	file_arista_subscriptions_subscriptions_proto_goTypes = nil
	file_arista_subscriptions_subscriptions_proto_depIdxs = nil
}
