config:
  default: true
  MD003: { style: atx }
  MD007: { indent: 2 }
  MD013: false
  MD024: { siblings_only: true }
  MD025: { front_matter_title: "" }
  MD033: false
  MD034: false
  MD036: false
  MD041: false
  MD046: { style: fenced }
  MD047: true
  MD049: { style: underscore }
  MD050: { style: asterisk }
  MD058: false
  MD060: false

ignores:
  - node_modules
  - bin
  - dist
  - reports
  - .worktrees
  - .serena
