// Copyright (c) 2020 Arista Networks, Inc.  All rights reserved.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the COPYING file.

//
// Code generated by boomtown. DO NOT EDIT.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: arista/changecontrol.v1/services.gen.proto

package changecontrolv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApproveConfigService_GetOne_FullMethodName           = "/arista.changecontrol.v1.ApproveConfigService/GetOne"
	ApproveConfigService_GetSome_FullMethodName          = "/arista.changecontrol.v1.ApproveConfigService/GetSome"
	ApproveConfigService_GetAll_FullMethodName           = "/arista.changecontrol.v1.ApproveConfigService/GetAll"
	ApproveConfigService_Subscribe_FullMethodName        = "/arista.changecontrol.v1.ApproveConfigService/Subscribe"
	ApproveConfigService_GetMeta_FullMethodName          = "/arista.changecontrol.v1.ApproveConfigService/GetMeta"
	ApproveConfigService_SubscribeMeta_FullMethodName    = "/arista.changecontrol.v1.ApproveConfigService/SubscribeMeta"
	ApproveConfigService_Set_FullMethodName              = "/arista.changecontrol.v1.ApproveConfigService/Set"
	ApproveConfigService_SetSome_FullMethodName          = "/arista.changecontrol.v1.ApproveConfigService/SetSome"
	ApproveConfigService_Delete_FullMethodName           = "/arista.changecontrol.v1.ApproveConfigService/Delete"
	ApproveConfigService_DeleteSome_FullMethodName       = "/arista.changecontrol.v1.ApproveConfigService/DeleteSome"
	ApproveConfigService_DeleteAll_FullMethodName        = "/arista.changecontrol.v1.ApproveConfigService/DeleteAll"
	ApproveConfigService_GetAllBatched_FullMethodName    = "/arista.changecontrol.v1.ApproveConfigService/GetAllBatched"
	ApproveConfigService_SubscribeBatched_FullMethodName = "/arista.changecontrol.v1.ApproveConfigService/SubscribeBatched"
)

// ApproveConfigServiceClient is the client API for ApproveConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApproveConfigServiceClient interface {
	GetOne(ctx context.Context, in *ApproveConfigRequest, opts ...grpc.CallOption) (*ApproveConfigResponse, error)
	GetSome(ctx context.Context, in *ApproveConfigSomeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApproveConfigSomeResponse], error)
	GetAll(ctx context.Context, in *ApproveConfigStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApproveConfigStreamResponse], error)
	Subscribe(ctx context.Context, in *ApproveConfigStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApproveConfigStreamResponse], error)
	GetMeta(ctx context.Context, in *ApproveConfigStreamRequest, opts ...grpc.CallOption) (*MetaResponse, error)
	SubscribeMeta(ctx context.Context, in *ApproveConfigStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetaResponse], error)
	Set(ctx context.Context, in *ApproveConfigSetRequest, opts ...grpc.CallOption) (*ApproveConfigSetResponse, error)
	SetSome(ctx context.Context, in *ApproveConfigSetSomeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApproveConfigSetSomeResponse], error)
	Delete(ctx context.Context, in *ApproveConfigDeleteRequest, opts ...grpc.CallOption) (*ApproveConfigDeleteResponse, error)
	DeleteSome(ctx context.Context, in *ApproveConfigDeleteSomeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApproveConfigDeleteSomeResponse], error)
	DeleteAll(ctx context.Context, in *ApproveConfigDeleteAllRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApproveConfigDeleteAllResponse], error)
	GetAllBatched(ctx context.Context, in *ApproveConfigBatchedStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApproveConfigBatchedStreamResponse], error)
	SubscribeBatched(ctx context.Context, in *ApproveConfigBatchedStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApproveConfigBatchedStreamResponse], error)
}

type approveConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApproveConfigServiceClient(cc grpc.ClientConnInterface) ApproveConfigServiceClient {
	return &approveConfigServiceClient{cc}
}

func (c *approveConfigServiceClient) GetOne(ctx context.Context, in *ApproveConfigRequest, opts ...grpc.CallOption) (*ApproveConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveConfigResponse)
	err := c.cc.Invoke(ctx, ApproveConfigService_GetOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approveConfigServiceClient) GetSome(ctx context.Context, in *ApproveConfigSomeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApproveConfigSomeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApproveConfigService_ServiceDesc.Streams[0], ApproveConfigService_GetSome_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ApproveConfigSomeRequest, ApproveConfigSomeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApproveConfigService_GetSomeClient = grpc.ServerStreamingClient[ApproveConfigSomeResponse]

func (c *approveConfigServiceClient) GetAll(ctx context.Context, in *ApproveConfigStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApproveConfigStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApproveConfigService_ServiceDesc.Streams[1], ApproveConfigService_GetAll_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ApproveConfigStreamRequest, ApproveConfigStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApproveConfigService_GetAllClient = grpc.ServerStreamingClient[ApproveConfigStreamResponse]

func (c *approveConfigServiceClient) Subscribe(ctx context.Context, in *ApproveConfigStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApproveConfigStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApproveConfigService_ServiceDesc.Streams[2], ApproveConfigService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ApproveConfigStreamRequest, ApproveConfigStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApproveConfigService_SubscribeClient = grpc.ServerStreamingClient[ApproveConfigStreamResponse]

func (c *approveConfigServiceClient) GetMeta(ctx context.Context, in *ApproveConfigStreamRequest, opts ...grpc.CallOption) (*MetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetaResponse)
	err := c.cc.Invoke(ctx, ApproveConfigService_GetMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approveConfigServiceClient) SubscribeMeta(ctx context.Context, in *ApproveConfigStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetaResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApproveConfigService_ServiceDesc.Streams[3], ApproveConfigService_SubscribeMeta_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ApproveConfigStreamRequest, MetaResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApproveConfigService_SubscribeMetaClient = grpc.ServerStreamingClient[MetaResponse]

func (c *approveConfigServiceClient) Set(ctx context.Context, in *ApproveConfigSetRequest, opts ...grpc.CallOption) (*ApproveConfigSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveConfigSetResponse)
	err := c.cc.Invoke(ctx, ApproveConfigService_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approveConfigServiceClient) SetSome(ctx context.Context, in *ApproveConfigSetSomeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApproveConfigSetSomeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApproveConfigService_ServiceDesc.Streams[4], ApproveConfigService_SetSome_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ApproveConfigSetSomeRequest, ApproveConfigSetSomeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApproveConfigService_SetSomeClient = grpc.ServerStreamingClient[ApproveConfigSetSomeResponse]

func (c *approveConfigServiceClient) Delete(ctx context.Context, in *ApproveConfigDeleteRequest, opts ...grpc.CallOption) (*ApproveConfigDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveConfigDeleteResponse)
	err := c.cc.Invoke(ctx, ApproveConfigService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approveConfigServiceClient) DeleteSome(ctx context.Context, in *ApproveConfigDeleteSomeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApproveConfigDeleteSomeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApproveConfigService_ServiceDesc.Streams[5], ApproveConfigService_DeleteSome_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ApproveConfigDeleteSomeRequest, ApproveConfigDeleteSomeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApproveConfigService_DeleteSomeClient = grpc.ServerStreamingClient[ApproveConfigDeleteSomeResponse]

func (c *approveConfigServiceClient) DeleteAll(ctx context.Context, in *ApproveConfigDeleteAllRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApproveConfigDeleteAllResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApproveConfigService_ServiceDesc.Streams[6], ApproveConfigService_DeleteAll_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ApproveConfigDeleteAllRequest, ApproveConfigDeleteAllResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApproveConfigService_DeleteAllClient = grpc.ServerStreamingClient[ApproveConfigDeleteAllResponse]

func (c *approveConfigServiceClient) GetAllBatched(ctx context.Context, in *ApproveConfigBatchedStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApproveConfigBatchedStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApproveConfigService_ServiceDesc.Streams[7], ApproveConfigService_GetAllBatched_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ApproveConfigBatchedStreamRequest, ApproveConfigBatchedStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApproveConfigService_GetAllBatchedClient = grpc.ServerStreamingClient[ApproveConfigBatchedStreamResponse]

func (c *approveConfigServiceClient) SubscribeBatched(ctx context.Context, in *ApproveConfigBatchedStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApproveConfigBatchedStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApproveConfigService_ServiceDesc.Streams[8], ApproveConfigService_SubscribeBatched_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ApproveConfigBatchedStreamRequest, ApproveConfigBatchedStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApproveConfigService_SubscribeBatchedClient = grpc.ServerStreamingClient[ApproveConfigBatchedStreamResponse]

// ApproveConfigServiceServer is the server API for ApproveConfigService service.
// All implementations should embed UnimplementedApproveConfigServiceServer
// for forward compatibility.
type ApproveConfigServiceServer interface {
	GetOne(context.Context, *ApproveConfigRequest) (*ApproveConfigResponse, error)
	GetSome(*ApproveConfigSomeRequest, grpc.ServerStreamingServer[ApproveConfigSomeResponse]) error
	GetAll(*ApproveConfigStreamRequest, grpc.ServerStreamingServer[ApproveConfigStreamResponse]) error
	Subscribe(*ApproveConfigStreamRequest, grpc.ServerStreamingServer[ApproveConfigStreamResponse]) error
	GetMeta(context.Context, *ApproveConfigStreamRequest) (*MetaResponse, error)
	SubscribeMeta(*ApproveConfigStreamRequest, grpc.ServerStreamingServer[MetaResponse]) error
	Set(context.Context, *ApproveConfigSetRequest) (*ApproveConfigSetResponse, error)
	SetSome(*ApproveConfigSetSomeRequest, grpc.ServerStreamingServer[ApproveConfigSetSomeResponse]) error
	Delete(context.Context, *ApproveConfigDeleteRequest) (*ApproveConfigDeleteResponse, error)
	DeleteSome(*ApproveConfigDeleteSomeRequest, grpc.ServerStreamingServer[ApproveConfigDeleteSomeResponse]) error
	DeleteAll(*ApproveConfigDeleteAllRequest, grpc.ServerStreamingServer[ApproveConfigDeleteAllResponse]) error
	GetAllBatched(*ApproveConfigBatchedStreamRequest, grpc.ServerStreamingServer[ApproveConfigBatchedStreamResponse]) error
	SubscribeBatched(*ApproveConfigBatchedStreamRequest, grpc.ServerStreamingServer[ApproveConfigBatchedStreamResponse]) error
}

// UnimplementedApproveConfigServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApproveConfigServiceServer struct{}

func (UnimplementedApproveConfigServiceServer) GetOne(context.Context, *ApproveConfigRequest) (*ApproveConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOne not implemented")
}
func (UnimplementedApproveConfigServiceServer) GetSome(*ApproveConfigSomeRequest, grpc.ServerStreamingServer[ApproveConfigSomeResponse]) error {
	return status.Error(codes.Unimplemented, "method GetSome not implemented")
}
func (UnimplementedApproveConfigServiceServer) GetAll(*ApproveConfigStreamRequest, grpc.ServerStreamingServer[ApproveConfigStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedApproveConfigServiceServer) Subscribe(*ApproveConfigStreamRequest, grpc.ServerStreamingServer[ApproveConfigStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedApproveConfigServiceServer) GetMeta(context.Context, *ApproveConfigStreamRequest) (*MetaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeta not implemented")
}
func (UnimplementedApproveConfigServiceServer) SubscribeMeta(*ApproveConfigStreamRequest, grpc.ServerStreamingServer[MetaResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeMeta not implemented")
}
func (UnimplementedApproveConfigServiceServer) Set(context.Context, *ApproveConfigSetRequest) (*ApproveConfigSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedApproveConfigServiceServer) SetSome(*ApproveConfigSetSomeRequest, grpc.ServerStreamingServer[ApproveConfigSetSomeResponse]) error {
	return status.Error(codes.Unimplemented, "method SetSome not implemented")
}
func (UnimplementedApproveConfigServiceServer) Delete(context.Context, *ApproveConfigDeleteRequest) (*ApproveConfigDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedApproveConfigServiceServer) DeleteSome(*ApproveConfigDeleteSomeRequest, grpc.ServerStreamingServer[ApproveConfigDeleteSomeResponse]) error {
	return status.Error(codes.Unimplemented, "method DeleteSome not implemented")
}
func (UnimplementedApproveConfigServiceServer) DeleteAll(*ApproveConfigDeleteAllRequest, grpc.ServerStreamingServer[ApproveConfigDeleteAllResponse]) error {
	return status.Error(codes.Unimplemented, "method DeleteAll not implemented")
}
func (UnimplementedApproveConfigServiceServer) GetAllBatched(*ApproveConfigBatchedStreamRequest, grpc.ServerStreamingServer[ApproveConfigBatchedStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method GetAllBatched not implemented")
}
func (UnimplementedApproveConfigServiceServer) SubscribeBatched(*ApproveConfigBatchedStreamRequest, grpc.ServerStreamingServer[ApproveConfigBatchedStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeBatched not implemented")
}
func (UnimplementedApproveConfigServiceServer) testEmbeddedByValue() {}

// UnsafeApproveConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApproveConfigServiceServer will
// result in compilation errors.
type UnsafeApproveConfigServiceServer interface {
	mustEmbedUnimplementedApproveConfigServiceServer()
}

func RegisterApproveConfigServiceServer(s grpc.ServiceRegistrar, srv ApproveConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedApproveConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApproveConfigService_ServiceDesc, srv)
}

func _ApproveConfigService_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApproveConfigServiceServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApproveConfigService_GetOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApproveConfigServiceServer).GetOne(ctx, req.(*ApproveConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApproveConfigService_GetSome_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ApproveConfigSomeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApproveConfigServiceServer).GetSome(m, &grpc.GenericServerStream[ApproveConfigSomeRequest, ApproveConfigSomeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApproveConfigService_GetSomeServer = grpc.ServerStreamingServer[ApproveConfigSomeResponse]

func _ApproveConfigService_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ApproveConfigStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApproveConfigServiceServer).GetAll(m, &grpc.GenericServerStream[ApproveConfigStreamRequest, ApproveConfigStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApproveConfigService_GetAllServer = grpc.ServerStreamingServer[ApproveConfigStreamResponse]

func _ApproveConfigService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ApproveConfigStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApproveConfigServiceServer).Subscribe(m, &grpc.GenericServerStream[ApproveConfigStreamRequest, ApproveConfigStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApproveConfigService_SubscribeServer = grpc.ServerStreamingServer[ApproveConfigStreamResponse]

func _ApproveConfigService_GetMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveConfigStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApproveConfigServiceServer).GetMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApproveConfigService_GetMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApproveConfigServiceServer).GetMeta(ctx, req.(*ApproveConfigStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApproveConfigService_SubscribeMeta_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ApproveConfigStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApproveConfigServiceServer).SubscribeMeta(m, &grpc.GenericServerStream[ApproveConfigStreamRequest, MetaResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApproveConfigService_SubscribeMetaServer = grpc.ServerStreamingServer[MetaResponse]

func _ApproveConfigService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveConfigSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApproveConfigServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApproveConfigService_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApproveConfigServiceServer).Set(ctx, req.(*ApproveConfigSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApproveConfigService_SetSome_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ApproveConfigSetSomeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApproveConfigServiceServer).SetSome(m, &grpc.GenericServerStream[ApproveConfigSetSomeRequest, ApproveConfigSetSomeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApproveConfigService_SetSomeServer = grpc.ServerStreamingServer[ApproveConfigSetSomeResponse]

func _ApproveConfigService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveConfigDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApproveConfigServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApproveConfigService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApproveConfigServiceServer).Delete(ctx, req.(*ApproveConfigDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApproveConfigService_DeleteSome_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ApproveConfigDeleteSomeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApproveConfigServiceServer).DeleteSome(m, &grpc.GenericServerStream[ApproveConfigDeleteSomeRequest, ApproveConfigDeleteSomeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApproveConfigService_DeleteSomeServer = grpc.ServerStreamingServer[ApproveConfigDeleteSomeResponse]

func _ApproveConfigService_DeleteAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ApproveConfigDeleteAllRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApproveConfigServiceServer).DeleteAll(m, &grpc.GenericServerStream[ApproveConfigDeleteAllRequest, ApproveConfigDeleteAllResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApproveConfigService_DeleteAllServer = grpc.ServerStreamingServer[ApproveConfigDeleteAllResponse]

func _ApproveConfigService_GetAllBatched_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ApproveConfigBatchedStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApproveConfigServiceServer).GetAllBatched(m, &grpc.GenericServerStream[ApproveConfigBatchedStreamRequest, ApproveConfigBatchedStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApproveConfigService_GetAllBatchedServer = grpc.ServerStreamingServer[ApproveConfigBatchedStreamResponse]

func _ApproveConfigService_SubscribeBatched_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ApproveConfigBatchedStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApproveConfigServiceServer).SubscribeBatched(m, &grpc.GenericServerStream[ApproveConfigBatchedStreamRequest, ApproveConfigBatchedStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApproveConfigService_SubscribeBatchedServer = grpc.ServerStreamingServer[ApproveConfigBatchedStreamResponse]

// ApproveConfigService_ServiceDesc is the grpc.ServiceDesc for ApproveConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApproveConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arista.changecontrol.v1.ApproveConfigService",
	HandlerType: (*ApproveConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOne",
			Handler:    _ApproveConfigService_GetOne_Handler,
		},
		{
			MethodName: "GetMeta",
			Handler:    _ApproveConfigService_GetMeta_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _ApproveConfigService_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ApproveConfigService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSome",
			Handler:       _ApproveConfigService_GetSome_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAll",
			Handler:       _ApproveConfigService_GetAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _ApproveConfigService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeMeta",
			Handler:       _ApproveConfigService_SubscribeMeta_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SetSome",
			Handler:       _ApproveConfigService_SetSome_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DeleteSome",
			Handler:       _ApproveConfigService_DeleteSome_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DeleteAll",
			Handler:       _ApproveConfigService_DeleteAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllBatched",
			Handler:       _ApproveConfigService_GetAllBatched_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeBatched",
			Handler:       _ApproveConfigService_SubscribeBatched_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "arista/changecontrol.v1/services.gen.proto",
}

const (
	ChangeControlService_GetOne_FullMethodName           = "/arista.changecontrol.v1.ChangeControlService/GetOne"
	ChangeControlService_GetSome_FullMethodName          = "/arista.changecontrol.v1.ChangeControlService/GetSome"
	ChangeControlService_GetAll_FullMethodName           = "/arista.changecontrol.v1.ChangeControlService/GetAll"
	ChangeControlService_Subscribe_FullMethodName        = "/arista.changecontrol.v1.ChangeControlService/Subscribe"
	ChangeControlService_GetMeta_FullMethodName          = "/arista.changecontrol.v1.ChangeControlService/GetMeta"
	ChangeControlService_SubscribeMeta_FullMethodName    = "/arista.changecontrol.v1.ChangeControlService/SubscribeMeta"
	ChangeControlService_GetAllBatched_FullMethodName    = "/arista.changecontrol.v1.ChangeControlService/GetAllBatched"
	ChangeControlService_SubscribeBatched_FullMethodName = "/arista.changecontrol.v1.ChangeControlService/SubscribeBatched"
)

// ChangeControlServiceClient is the client API for ChangeControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChangeControlServiceClient interface {
	GetOne(ctx context.Context, in *ChangeControlRequest, opts ...grpc.CallOption) (*ChangeControlResponse, error)
	GetSome(ctx context.Context, in *ChangeControlSomeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlSomeResponse], error)
	GetAll(ctx context.Context, in *ChangeControlStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlStreamResponse], error)
	Subscribe(ctx context.Context, in *ChangeControlStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlStreamResponse], error)
	GetMeta(ctx context.Context, in *ChangeControlStreamRequest, opts ...grpc.CallOption) (*MetaResponse, error)
	SubscribeMeta(ctx context.Context, in *ChangeControlStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetaResponse], error)
	GetAllBatched(ctx context.Context, in *ChangeControlBatchedStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlBatchedStreamResponse], error)
	SubscribeBatched(ctx context.Context, in *ChangeControlBatchedStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlBatchedStreamResponse], error)
}

type changeControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChangeControlServiceClient(cc grpc.ClientConnInterface) ChangeControlServiceClient {
	return &changeControlServiceClient{cc}
}

func (c *changeControlServiceClient) GetOne(ctx context.Context, in *ChangeControlRequest, opts ...grpc.CallOption) (*ChangeControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeControlResponse)
	err := c.cc.Invoke(ctx, ChangeControlService_GetOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeControlServiceClient) GetSome(ctx context.Context, in *ChangeControlSomeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlSomeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChangeControlService_ServiceDesc.Streams[0], ChangeControlService_GetSome_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeControlSomeRequest, ChangeControlSomeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlService_GetSomeClient = grpc.ServerStreamingClient[ChangeControlSomeResponse]

func (c *changeControlServiceClient) GetAll(ctx context.Context, in *ChangeControlStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChangeControlService_ServiceDesc.Streams[1], ChangeControlService_GetAll_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeControlStreamRequest, ChangeControlStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlService_GetAllClient = grpc.ServerStreamingClient[ChangeControlStreamResponse]

func (c *changeControlServiceClient) Subscribe(ctx context.Context, in *ChangeControlStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChangeControlService_ServiceDesc.Streams[2], ChangeControlService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeControlStreamRequest, ChangeControlStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlService_SubscribeClient = grpc.ServerStreamingClient[ChangeControlStreamResponse]

func (c *changeControlServiceClient) GetMeta(ctx context.Context, in *ChangeControlStreamRequest, opts ...grpc.CallOption) (*MetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetaResponse)
	err := c.cc.Invoke(ctx, ChangeControlService_GetMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeControlServiceClient) SubscribeMeta(ctx context.Context, in *ChangeControlStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetaResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChangeControlService_ServiceDesc.Streams[3], ChangeControlService_SubscribeMeta_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeControlStreamRequest, MetaResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlService_SubscribeMetaClient = grpc.ServerStreamingClient[MetaResponse]

func (c *changeControlServiceClient) GetAllBatched(ctx context.Context, in *ChangeControlBatchedStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlBatchedStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChangeControlService_ServiceDesc.Streams[4], ChangeControlService_GetAllBatched_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeControlBatchedStreamRequest, ChangeControlBatchedStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlService_GetAllBatchedClient = grpc.ServerStreamingClient[ChangeControlBatchedStreamResponse]

func (c *changeControlServiceClient) SubscribeBatched(ctx context.Context, in *ChangeControlBatchedStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlBatchedStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChangeControlService_ServiceDesc.Streams[5], ChangeControlService_SubscribeBatched_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeControlBatchedStreamRequest, ChangeControlBatchedStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlService_SubscribeBatchedClient = grpc.ServerStreamingClient[ChangeControlBatchedStreamResponse]

// ChangeControlServiceServer is the server API for ChangeControlService service.
// All implementations should embed UnimplementedChangeControlServiceServer
// for forward compatibility.
type ChangeControlServiceServer interface {
	GetOne(context.Context, *ChangeControlRequest) (*ChangeControlResponse, error)
	GetSome(*ChangeControlSomeRequest, grpc.ServerStreamingServer[ChangeControlSomeResponse]) error
	GetAll(*ChangeControlStreamRequest, grpc.ServerStreamingServer[ChangeControlStreamResponse]) error
	Subscribe(*ChangeControlStreamRequest, grpc.ServerStreamingServer[ChangeControlStreamResponse]) error
	GetMeta(context.Context, *ChangeControlStreamRequest) (*MetaResponse, error)
	SubscribeMeta(*ChangeControlStreamRequest, grpc.ServerStreamingServer[MetaResponse]) error
	GetAllBatched(*ChangeControlBatchedStreamRequest, grpc.ServerStreamingServer[ChangeControlBatchedStreamResponse]) error
	SubscribeBatched(*ChangeControlBatchedStreamRequest, grpc.ServerStreamingServer[ChangeControlBatchedStreamResponse]) error
}

// UnimplementedChangeControlServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChangeControlServiceServer struct{}

func (UnimplementedChangeControlServiceServer) GetOne(context.Context, *ChangeControlRequest) (*ChangeControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOne not implemented")
}
func (UnimplementedChangeControlServiceServer) GetSome(*ChangeControlSomeRequest, grpc.ServerStreamingServer[ChangeControlSomeResponse]) error {
	return status.Error(codes.Unimplemented, "method GetSome not implemented")
}
func (UnimplementedChangeControlServiceServer) GetAll(*ChangeControlStreamRequest, grpc.ServerStreamingServer[ChangeControlStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedChangeControlServiceServer) Subscribe(*ChangeControlStreamRequest, grpc.ServerStreamingServer[ChangeControlStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedChangeControlServiceServer) GetMeta(context.Context, *ChangeControlStreamRequest) (*MetaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeta not implemented")
}
func (UnimplementedChangeControlServiceServer) SubscribeMeta(*ChangeControlStreamRequest, grpc.ServerStreamingServer[MetaResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeMeta not implemented")
}
func (UnimplementedChangeControlServiceServer) GetAllBatched(*ChangeControlBatchedStreamRequest, grpc.ServerStreamingServer[ChangeControlBatchedStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method GetAllBatched not implemented")
}
func (UnimplementedChangeControlServiceServer) SubscribeBatched(*ChangeControlBatchedStreamRequest, grpc.ServerStreamingServer[ChangeControlBatchedStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeBatched not implemented")
}
func (UnimplementedChangeControlServiceServer) testEmbeddedByValue() {}

// UnsafeChangeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChangeControlServiceServer will
// result in compilation errors.
type UnsafeChangeControlServiceServer interface {
	mustEmbedUnimplementedChangeControlServiceServer()
}

func RegisterChangeControlServiceServer(s grpc.ServiceRegistrar, srv ChangeControlServiceServer) {
	// If the following call panics, it indicates UnimplementedChangeControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChangeControlService_ServiceDesc, srv)
}

func _ChangeControlService_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeControlServiceServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeControlService_GetOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeControlServiceServer).GetOne(ctx, req.(*ChangeControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeControlService_GetSome_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChangeControlSomeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangeControlServiceServer).GetSome(m, &grpc.GenericServerStream[ChangeControlSomeRequest, ChangeControlSomeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlService_GetSomeServer = grpc.ServerStreamingServer[ChangeControlSomeResponse]

func _ChangeControlService_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChangeControlStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangeControlServiceServer).GetAll(m, &grpc.GenericServerStream[ChangeControlStreamRequest, ChangeControlStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlService_GetAllServer = grpc.ServerStreamingServer[ChangeControlStreamResponse]

func _ChangeControlService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChangeControlStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangeControlServiceServer).Subscribe(m, &grpc.GenericServerStream[ChangeControlStreamRequest, ChangeControlStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlService_SubscribeServer = grpc.ServerStreamingServer[ChangeControlStreamResponse]

func _ChangeControlService_GetMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeControlStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeControlServiceServer).GetMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeControlService_GetMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeControlServiceServer).GetMeta(ctx, req.(*ChangeControlStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeControlService_SubscribeMeta_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChangeControlStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangeControlServiceServer).SubscribeMeta(m, &grpc.GenericServerStream[ChangeControlStreamRequest, MetaResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlService_SubscribeMetaServer = grpc.ServerStreamingServer[MetaResponse]

func _ChangeControlService_GetAllBatched_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChangeControlBatchedStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangeControlServiceServer).GetAllBatched(m, &grpc.GenericServerStream[ChangeControlBatchedStreamRequest, ChangeControlBatchedStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlService_GetAllBatchedServer = grpc.ServerStreamingServer[ChangeControlBatchedStreamResponse]

func _ChangeControlService_SubscribeBatched_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChangeControlBatchedStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangeControlServiceServer).SubscribeBatched(m, &grpc.GenericServerStream[ChangeControlBatchedStreamRequest, ChangeControlBatchedStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlService_SubscribeBatchedServer = grpc.ServerStreamingServer[ChangeControlBatchedStreamResponse]

// ChangeControlService_ServiceDesc is the grpc.ServiceDesc for ChangeControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChangeControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arista.changecontrol.v1.ChangeControlService",
	HandlerType: (*ChangeControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOne",
			Handler:    _ChangeControlService_GetOne_Handler,
		},
		{
			MethodName: "GetMeta",
			Handler:    _ChangeControlService_GetMeta_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSome",
			Handler:       _ChangeControlService_GetSome_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAll",
			Handler:       _ChangeControlService_GetAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _ChangeControlService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeMeta",
			Handler:       _ChangeControlService_SubscribeMeta_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllBatched",
			Handler:       _ChangeControlService_GetAllBatched_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeBatched",
			Handler:       _ChangeControlService_SubscribeBatched_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "arista/changecontrol.v1/services.gen.proto",
}

const (
	ChangeControlConfigService_GetOne_FullMethodName           = "/arista.changecontrol.v1.ChangeControlConfigService/GetOne"
	ChangeControlConfigService_GetSome_FullMethodName          = "/arista.changecontrol.v1.ChangeControlConfigService/GetSome"
	ChangeControlConfigService_GetAll_FullMethodName           = "/arista.changecontrol.v1.ChangeControlConfigService/GetAll"
	ChangeControlConfigService_Subscribe_FullMethodName        = "/arista.changecontrol.v1.ChangeControlConfigService/Subscribe"
	ChangeControlConfigService_GetMeta_FullMethodName          = "/arista.changecontrol.v1.ChangeControlConfigService/GetMeta"
	ChangeControlConfigService_SubscribeMeta_FullMethodName    = "/arista.changecontrol.v1.ChangeControlConfigService/SubscribeMeta"
	ChangeControlConfigService_Set_FullMethodName              = "/arista.changecontrol.v1.ChangeControlConfigService/Set"
	ChangeControlConfigService_SetSome_FullMethodName          = "/arista.changecontrol.v1.ChangeControlConfigService/SetSome"
	ChangeControlConfigService_Delete_FullMethodName           = "/arista.changecontrol.v1.ChangeControlConfigService/Delete"
	ChangeControlConfigService_DeleteSome_FullMethodName       = "/arista.changecontrol.v1.ChangeControlConfigService/DeleteSome"
	ChangeControlConfigService_DeleteAll_FullMethodName        = "/arista.changecontrol.v1.ChangeControlConfigService/DeleteAll"
	ChangeControlConfigService_GetAllBatched_FullMethodName    = "/arista.changecontrol.v1.ChangeControlConfigService/GetAllBatched"
	ChangeControlConfigService_SubscribeBatched_FullMethodName = "/arista.changecontrol.v1.ChangeControlConfigService/SubscribeBatched"
)

// ChangeControlConfigServiceClient is the client API for ChangeControlConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChangeControlConfigServiceClient interface {
	GetOne(ctx context.Context, in *ChangeControlConfigRequest, opts ...grpc.CallOption) (*ChangeControlConfigResponse, error)
	GetSome(ctx context.Context, in *ChangeControlConfigSomeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlConfigSomeResponse], error)
	GetAll(ctx context.Context, in *ChangeControlConfigStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlConfigStreamResponse], error)
	Subscribe(ctx context.Context, in *ChangeControlConfigStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlConfigStreamResponse], error)
	GetMeta(ctx context.Context, in *ChangeControlConfigStreamRequest, opts ...grpc.CallOption) (*MetaResponse, error)
	SubscribeMeta(ctx context.Context, in *ChangeControlConfigStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetaResponse], error)
	Set(ctx context.Context, in *ChangeControlConfigSetRequest, opts ...grpc.CallOption) (*ChangeControlConfigSetResponse, error)
	SetSome(ctx context.Context, in *ChangeControlConfigSetSomeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlConfigSetSomeResponse], error)
	Delete(ctx context.Context, in *ChangeControlConfigDeleteRequest, opts ...grpc.CallOption) (*ChangeControlConfigDeleteResponse, error)
	DeleteSome(ctx context.Context, in *ChangeControlConfigDeleteSomeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlConfigDeleteSomeResponse], error)
	DeleteAll(ctx context.Context, in *ChangeControlConfigDeleteAllRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlConfigDeleteAllResponse], error)
	GetAllBatched(ctx context.Context, in *ChangeControlConfigBatchedStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlConfigBatchedStreamResponse], error)
	SubscribeBatched(ctx context.Context, in *ChangeControlConfigBatchedStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlConfigBatchedStreamResponse], error)
}

type changeControlConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChangeControlConfigServiceClient(cc grpc.ClientConnInterface) ChangeControlConfigServiceClient {
	return &changeControlConfigServiceClient{cc}
}

func (c *changeControlConfigServiceClient) GetOne(ctx context.Context, in *ChangeControlConfigRequest, opts ...grpc.CallOption) (*ChangeControlConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeControlConfigResponse)
	err := c.cc.Invoke(ctx, ChangeControlConfigService_GetOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeControlConfigServiceClient) GetSome(ctx context.Context, in *ChangeControlConfigSomeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlConfigSomeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChangeControlConfigService_ServiceDesc.Streams[0], ChangeControlConfigService_GetSome_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeControlConfigSomeRequest, ChangeControlConfigSomeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlConfigService_GetSomeClient = grpc.ServerStreamingClient[ChangeControlConfigSomeResponse]

func (c *changeControlConfigServiceClient) GetAll(ctx context.Context, in *ChangeControlConfigStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlConfigStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChangeControlConfigService_ServiceDesc.Streams[1], ChangeControlConfigService_GetAll_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeControlConfigStreamRequest, ChangeControlConfigStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlConfigService_GetAllClient = grpc.ServerStreamingClient[ChangeControlConfigStreamResponse]

func (c *changeControlConfigServiceClient) Subscribe(ctx context.Context, in *ChangeControlConfigStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlConfigStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChangeControlConfigService_ServiceDesc.Streams[2], ChangeControlConfigService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeControlConfigStreamRequest, ChangeControlConfigStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlConfigService_SubscribeClient = grpc.ServerStreamingClient[ChangeControlConfigStreamResponse]

func (c *changeControlConfigServiceClient) GetMeta(ctx context.Context, in *ChangeControlConfigStreamRequest, opts ...grpc.CallOption) (*MetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetaResponse)
	err := c.cc.Invoke(ctx, ChangeControlConfigService_GetMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeControlConfigServiceClient) SubscribeMeta(ctx context.Context, in *ChangeControlConfigStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetaResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChangeControlConfigService_ServiceDesc.Streams[3], ChangeControlConfigService_SubscribeMeta_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeControlConfigStreamRequest, MetaResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlConfigService_SubscribeMetaClient = grpc.ServerStreamingClient[MetaResponse]

func (c *changeControlConfigServiceClient) Set(ctx context.Context, in *ChangeControlConfigSetRequest, opts ...grpc.CallOption) (*ChangeControlConfigSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeControlConfigSetResponse)
	err := c.cc.Invoke(ctx, ChangeControlConfigService_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeControlConfigServiceClient) SetSome(ctx context.Context, in *ChangeControlConfigSetSomeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlConfigSetSomeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChangeControlConfigService_ServiceDesc.Streams[4], ChangeControlConfigService_SetSome_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeControlConfigSetSomeRequest, ChangeControlConfigSetSomeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlConfigService_SetSomeClient = grpc.ServerStreamingClient[ChangeControlConfigSetSomeResponse]

func (c *changeControlConfigServiceClient) Delete(ctx context.Context, in *ChangeControlConfigDeleteRequest, opts ...grpc.CallOption) (*ChangeControlConfigDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeControlConfigDeleteResponse)
	err := c.cc.Invoke(ctx, ChangeControlConfigService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeControlConfigServiceClient) DeleteSome(ctx context.Context, in *ChangeControlConfigDeleteSomeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlConfigDeleteSomeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChangeControlConfigService_ServiceDesc.Streams[5], ChangeControlConfigService_DeleteSome_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeControlConfigDeleteSomeRequest, ChangeControlConfigDeleteSomeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlConfigService_DeleteSomeClient = grpc.ServerStreamingClient[ChangeControlConfigDeleteSomeResponse]

func (c *changeControlConfigServiceClient) DeleteAll(ctx context.Context, in *ChangeControlConfigDeleteAllRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlConfigDeleteAllResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChangeControlConfigService_ServiceDesc.Streams[6], ChangeControlConfigService_DeleteAll_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeControlConfigDeleteAllRequest, ChangeControlConfigDeleteAllResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlConfigService_DeleteAllClient = grpc.ServerStreamingClient[ChangeControlConfigDeleteAllResponse]

func (c *changeControlConfigServiceClient) GetAllBatched(ctx context.Context, in *ChangeControlConfigBatchedStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlConfigBatchedStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChangeControlConfigService_ServiceDesc.Streams[7], ChangeControlConfigService_GetAllBatched_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeControlConfigBatchedStreamRequest, ChangeControlConfigBatchedStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlConfigService_GetAllBatchedClient = grpc.ServerStreamingClient[ChangeControlConfigBatchedStreamResponse]

func (c *changeControlConfigServiceClient) SubscribeBatched(ctx context.Context, in *ChangeControlConfigBatchedStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeControlConfigBatchedStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChangeControlConfigService_ServiceDesc.Streams[8], ChangeControlConfigService_SubscribeBatched_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeControlConfigBatchedStreamRequest, ChangeControlConfigBatchedStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlConfigService_SubscribeBatchedClient = grpc.ServerStreamingClient[ChangeControlConfigBatchedStreamResponse]

// ChangeControlConfigServiceServer is the server API for ChangeControlConfigService service.
// All implementations should embed UnimplementedChangeControlConfigServiceServer
// for forward compatibility.
type ChangeControlConfigServiceServer interface {
	GetOne(context.Context, *ChangeControlConfigRequest) (*ChangeControlConfigResponse, error)
	GetSome(*ChangeControlConfigSomeRequest, grpc.ServerStreamingServer[ChangeControlConfigSomeResponse]) error
	GetAll(*ChangeControlConfigStreamRequest, grpc.ServerStreamingServer[ChangeControlConfigStreamResponse]) error
	Subscribe(*ChangeControlConfigStreamRequest, grpc.ServerStreamingServer[ChangeControlConfigStreamResponse]) error
	GetMeta(context.Context, *ChangeControlConfigStreamRequest) (*MetaResponse, error)
	SubscribeMeta(*ChangeControlConfigStreamRequest, grpc.ServerStreamingServer[MetaResponse]) error
	Set(context.Context, *ChangeControlConfigSetRequest) (*ChangeControlConfigSetResponse, error)
	SetSome(*ChangeControlConfigSetSomeRequest, grpc.ServerStreamingServer[ChangeControlConfigSetSomeResponse]) error
	Delete(context.Context, *ChangeControlConfigDeleteRequest) (*ChangeControlConfigDeleteResponse, error)
	DeleteSome(*ChangeControlConfigDeleteSomeRequest, grpc.ServerStreamingServer[ChangeControlConfigDeleteSomeResponse]) error
	DeleteAll(*ChangeControlConfigDeleteAllRequest, grpc.ServerStreamingServer[ChangeControlConfigDeleteAllResponse]) error
	GetAllBatched(*ChangeControlConfigBatchedStreamRequest, grpc.ServerStreamingServer[ChangeControlConfigBatchedStreamResponse]) error
	SubscribeBatched(*ChangeControlConfigBatchedStreamRequest, grpc.ServerStreamingServer[ChangeControlConfigBatchedStreamResponse]) error
}

// UnimplementedChangeControlConfigServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChangeControlConfigServiceServer struct{}

func (UnimplementedChangeControlConfigServiceServer) GetOne(context.Context, *ChangeControlConfigRequest) (*ChangeControlConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOne not implemented")
}
func (UnimplementedChangeControlConfigServiceServer) GetSome(*ChangeControlConfigSomeRequest, grpc.ServerStreamingServer[ChangeControlConfigSomeResponse]) error {
	return status.Error(codes.Unimplemented, "method GetSome not implemented")
}
func (UnimplementedChangeControlConfigServiceServer) GetAll(*ChangeControlConfigStreamRequest, grpc.ServerStreamingServer[ChangeControlConfigStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedChangeControlConfigServiceServer) Subscribe(*ChangeControlConfigStreamRequest, grpc.ServerStreamingServer[ChangeControlConfigStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedChangeControlConfigServiceServer) GetMeta(context.Context, *ChangeControlConfigStreamRequest) (*MetaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeta not implemented")
}
func (UnimplementedChangeControlConfigServiceServer) SubscribeMeta(*ChangeControlConfigStreamRequest, grpc.ServerStreamingServer[MetaResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeMeta not implemented")
}
func (UnimplementedChangeControlConfigServiceServer) Set(context.Context, *ChangeControlConfigSetRequest) (*ChangeControlConfigSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedChangeControlConfigServiceServer) SetSome(*ChangeControlConfigSetSomeRequest, grpc.ServerStreamingServer[ChangeControlConfigSetSomeResponse]) error {
	return status.Error(codes.Unimplemented, "method SetSome not implemented")
}
func (UnimplementedChangeControlConfigServiceServer) Delete(context.Context, *ChangeControlConfigDeleteRequest) (*ChangeControlConfigDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedChangeControlConfigServiceServer) DeleteSome(*ChangeControlConfigDeleteSomeRequest, grpc.ServerStreamingServer[ChangeControlConfigDeleteSomeResponse]) error {
	return status.Error(codes.Unimplemented, "method DeleteSome not implemented")
}
func (UnimplementedChangeControlConfigServiceServer) DeleteAll(*ChangeControlConfigDeleteAllRequest, grpc.ServerStreamingServer[ChangeControlConfigDeleteAllResponse]) error {
	return status.Error(codes.Unimplemented, "method DeleteAll not implemented")
}
func (UnimplementedChangeControlConfigServiceServer) GetAllBatched(*ChangeControlConfigBatchedStreamRequest, grpc.ServerStreamingServer[ChangeControlConfigBatchedStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method GetAllBatched not implemented")
}
func (UnimplementedChangeControlConfigServiceServer) SubscribeBatched(*ChangeControlConfigBatchedStreamRequest, grpc.ServerStreamingServer[ChangeControlConfigBatchedStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeBatched not implemented")
}
func (UnimplementedChangeControlConfigServiceServer) testEmbeddedByValue() {}

// UnsafeChangeControlConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChangeControlConfigServiceServer will
// result in compilation errors.
type UnsafeChangeControlConfigServiceServer interface {
	mustEmbedUnimplementedChangeControlConfigServiceServer()
}

func RegisterChangeControlConfigServiceServer(s grpc.ServiceRegistrar, srv ChangeControlConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedChangeControlConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChangeControlConfigService_ServiceDesc, srv)
}

func _ChangeControlConfigService_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeControlConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeControlConfigServiceServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeControlConfigService_GetOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeControlConfigServiceServer).GetOne(ctx, req.(*ChangeControlConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeControlConfigService_GetSome_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChangeControlConfigSomeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangeControlConfigServiceServer).GetSome(m, &grpc.GenericServerStream[ChangeControlConfigSomeRequest, ChangeControlConfigSomeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlConfigService_GetSomeServer = grpc.ServerStreamingServer[ChangeControlConfigSomeResponse]

func _ChangeControlConfigService_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChangeControlConfigStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangeControlConfigServiceServer).GetAll(m, &grpc.GenericServerStream[ChangeControlConfigStreamRequest, ChangeControlConfigStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlConfigService_GetAllServer = grpc.ServerStreamingServer[ChangeControlConfigStreamResponse]

func _ChangeControlConfigService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChangeControlConfigStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangeControlConfigServiceServer).Subscribe(m, &grpc.GenericServerStream[ChangeControlConfigStreamRequest, ChangeControlConfigStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlConfigService_SubscribeServer = grpc.ServerStreamingServer[ChangeControlConfigStreamResponse]

func _ChangeControlConfigService_GetMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeControlConfigStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeControlConfigServiceServer).GetMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeControlConfigService_GetMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeControlConfigServiceServer).GetMeta(ctx, req.(*ChangeControlConfigStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeControlConfigService_SubscribeMeta_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChangeControlConfigStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangeControlConfigServiceServer).SubscribeMeta(m, &grpc.GenericServerStream[ChangeControlConfigStreamRequest, MetaResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlConfigService_SubscribeMetaServer = grpc.ServerStreamingServer[MetaResponse]

func _ChangeControlConfigService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeControlConfigSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeControlConfigServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeControlConfigService_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeControlConfigServiceServer).Set(ctx, req.(*ChangeControlConfigSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeControlConfigService_SetSome_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChangeControlConfigSetSomeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangeControlConfigServiceServer).SetSome(m, &grpc.GenericServerStream[ChangeControlConfigSetSomeRequest, ChangeControlConfigSetSomeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlConfigService_SetSomeServer = grpc.ServerStreamingServer[ChangeControlConfigSetSomeResponse]

func _ChangeControlConfigService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeControlConfigDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeControlConfigServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeControlConfigService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeControlConfigServiceServer).Delete(ctx, req.(*ChangeControlConfigDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeControlConfigService_DeleteSome_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChangeControlConfigDeleteSomeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangeControlConfigServiceServer).DeleteSome(m, &grpc.GenericServerStream[ChangeControlConfigDeleteSomeRequest, ChangeControlConfigDeleteSomeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlConfigService_DeleteSomeServer = grpc.ServerStreamingServer[ChangeControlConfigDeleteSomeResponse]

func _ChangeControlConfigService_DeleteAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChangeControlConfigDeleteAllRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangeControlConfigServiceServer).DeleteAll(m, &grpc.GenericServerStream[ChangeControlConfigDeleteAllRequest, ChangeControlConfigDeleteAllResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlConfigService_DeleteAllServer = grpc.ServerStreamingServer[ChangeControlConfigDeleteAllResponse]

func _ChangeControlConfigService_GetAllBatched_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChangeControlConfigBatchedStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangeControlConfigServiceServer).GetAllBatched(m, &grpc.GenericServerStream[ChangeControlConfigBatchedStreamRequest, ChangeControlConfigBatchedStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlConfigService_GetAllBatchedServer = grpc.ServerStreamingServer[ChangeControlConfigBatchedStreamResponse]

func _ChangeControlConfigService_SubscribeBatched_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChangeControlConfigBatchedStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangeControlConfigServiceServer).SubscribeBatched(m, &grpc.GenericServerStream[ChangeControlConfigBatchedStreamRequest, ChangeControlConfigBatchedStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeControlConfigService_SubscribeBatchedServer = grpc.ServerStreamingServer[ChangeControlConfigBatchedStreamResponse]

// ChangeControlConfigService_ServiceDesc is the grpc.ServiceDesc for ChangeControlConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChangeControlConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arista.changecontrol.v1.ChangeControlConfigService",
	HandlerType: (*ChangeControlConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOne",
			Handler:    _ChangeControlConfigService_GetOne_Handler,
		},
		{
			MethodName: "GetMeta",
			Handler:    _ChangeControlConfigService_GetMeta_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _ChangeControlConfigService_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ChangeControlConfigService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSome",
			Handler:       _ChangeControlConfigService_GetSome_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAll",
			Handler:       _ChangeControlConfigService_GetAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _ChangeControlConfigService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeMeta",
			Handler:       _ChangeControlConfigService_SubscribeMeta_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SetSome",
			Handler:       _ChangeControlConfigService_SetSome_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DeleteSome",
			Handler:       _ChangeControlConfigService_DeleteSome_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DeleteAll",
			Handler:       _ChangeControlConfigService_DeleteAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllBatched",
			Handler:       _ChangeControlConfigService_GetAllBatched_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeBatched",
			Handler:       _ChangeControlConfigService_SubscribeBatched_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "arista/changecontrol.v1/services.gen.proto",
}
