// Copyright (c) 2021 Arista Networks, Inc.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the COPYING file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: fmp/deletes.proto

package fmp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeleteError defines the set of delete error types.
type DeleteError int32

const (
	// DELETE_ERROR_UNSPECIFIED indicates that the delete error
	// is not specified.
	DeleteError_DELETE_ERROR_UNSPECIFIED DeleteError = 0
	// DELETE_ERROR_UNAUTHORIZED indicates that the user is not authorized
	// to perform the specified delete.
	DeleteError_DELETE_ERROR_UNAUTHORIZED DeleteError = 1
	// DELETE_ERROR_INTERNAL indicates that the server encountered an
	// unrecoverable error on the specified delete.
	DeleteError_DELETE_ERROR_INTERNAL DeleteError = 2
	// DELETE_ERROR_UNDELETABLE_KEY indicates that the specified error is
	// not allowed by the service.
	DeleteError_DELETE_ERROR_UNDELETABLE_KEY DeleteError = 3
)

// Enum value maps for DeleteError.
var (
	DeleteError_name = map[int32]string{
		0: "DELETE_ERROR_UNSPECIFIED",
		1: "DELETE_ERROR_UNAUTHORIZED",
		2: "DELETE_ERROR_INTERNAL",
		3: "DELETE_ERROR_UNDELETABLE_KEY",
	}
	DeleteError_value = map[string]int32{
		"DELETE_ERROR_UNSPECIFIED":     0,
		"DELETE_ERROR_UNAUTHORIZED":    1,
		"DELETE_ERROR_INTERNAL":        2,
		"DELETE_ERROR_UNDELETABLE_KEY": 3,
	}
)

func (x DeleteError) Enum() *DeleteError {
	p := new(DeleteError)
	*p = x
	return p
}

func (x DeleteError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteError) Descriptor() protoreflect.EnumDescriptor {
	return file_fmp_deletes_proto_enumTypes[0].Descriptor()
}

func (DeleteError) Type() protoreflect.EnumType {
	return &file_fmp_deletes_proto_enumTypes[0]
}

func (x DeleteError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteError.Descriptor instead.
func (DeleteError) EnumDescriptor() ([]byte, []int) {
	return file_fmp_deletes_proto_rawDescGZIP(), []int{0}
}

var File_fmp_deletes_proto protoreflect.FileDescriptor

const file_fmp_deletes_proto_rawDesc = "" +
	"\n" +
	"\x11fmp/deletes.proto\x12\x03fmp*\x87\x01\n" +
	"\vDeleteError\x12\x1c\n" +
	"\x18DELETE_ERROR_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DELETE_ERROR_UNAUTHORIZED\x10\x01\x12\x19\n" +
	"\x15DELETE_ERROR_INTERNAL\x10\x02\x12 \n" +
	"\x1cDELETE_ERROR_UNDELETABLE_KEY\x10\x03B~\n" +
	"\acom.fmpB\fDeletesProtoP\x01Z9github.com/ioplane/terraform-provider-cvp/internal/pb/fmp\xa2\x02\x03FXX\xaa\x02\x03Fmp\xca\x02\x03Fmp\xe2\x02\x0fFmp\\GPBMetadata\xea\x02\x03Fmpb\x06proto3"

var (
	file_fmp_deletes_proto_rawDescOnce sync.Once
	file_fmp_deletes_proto_rawDescData []byte
)

func file_fmp_deletes_proto_rawDescGZIP() []byte {
	file_fmp_deletes_proto_rawDescOnce.Do(func() {
		file_fmp_deletes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fmp_deletes_proto_rawDesc), len(file_fmp_deletes_proto_rawDesc)))
	})
	return file_fmp_deletes_proto_rawDescData
}

var file_fmp_deletes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fmp_deletes_proto_goTypes = []any{
	(DeleteError)(0), // 0: fmp.DeleteError
}
var file_fmp_deletes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fmp_deletes_proto_init() }
func file_fmp_deletes_proto_init() {
	if File_fmp_deletes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fmp_deletes_proto_rawDesc), len(file_fmp_deletes_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fmp_deletes_proto_goTypes,
		DependencyIndexes: file_fmp_deletes_proto_depIdxs,
		EnumInfos:         file_fmp_deletes_proto_enumTypes,
	}.Build()
	File_fmp_deletes_proto = out.File
	file_fmp_deletes_proto_goTypes = nil
	file_fmp_deletes_proto_depIdxs = nil
}
