// Copyright (c) 2020 Arista Networks, Inc.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the COPYING file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: fmp/extensions.proto

package fmp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_fmp_extensions_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51423,
		Name:          "fmp.model",
		Tag:           "bytes,51423,opt,name=model",
		Filename:      "fmp/extensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         51424,
		Name:          "fmp.model_key",
		Tag:           "varint,51424,opt,name=model_key",
		Filename:      "fmp/extensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51425,
		Name:          "fmp.custom_filter",
		Tag:           "bytes,51425,opt,name=custom_filter",
		Filename:      "fmp/extensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         51426,
		Name:          "fmp.no_default_filter",
		Tag:           "varint,51426,opt,name=no_default_filter",
		Filename:      "fmp/extensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         51427,
		Name:          "fmp.require_set_key",
		Tag:           "varint,51427,opt,name=require_set_key",
		Filename:      "fmp/extensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51428,
		Name:          "fmp.unkeyed_model",
		Tag:           "bytes,51428,opt,name=unkeyed_model",
		Filename:      "fmp/extensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         51429,
		Name:          "fmp.paginated",
		Tag:           "varint,51429,opt,name=paginated",
		Filename:      "fmp/extensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51449,
		Name:          "fmp.child_resource",
		Tag:           "bytes,51449,opt,name=child_resource",
		Filename:      "fmp/extensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51450,
		Name:          "fmp.sortable",
		Tag:           "bytes,51450,opt,name=sortable",
		Filename:      "fmp/extensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51623,
		Name:          "fmp.disable_yang",
		Tag:           "bytes,51623,opt,name=disable_yang",
		Filename:      "fmp/extensions.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// TODO: will need an official number from Google, just like gNMI extensions
	//
	//	this works for now, though.
	//
	// optional string model = 51423;
	E_Model = &file_fmp_extensions_proto_extTypes[0]
	// optional bool model_key = 51424;
	E_ModelKey = &file_fmp_extensions_proto_extTypes[1]
	// optional string custom_filter = 51425;
	E_CustomFilter = &file_fmp_extensions_proto_extTypes[2]
	// optional bool no_default_filter = 51426;
	E_NoDefaultFilter = &file_fmp_extensions_proto_extTypes[3]
	// optional bool require_set_key = 51427;
	E_RequireSetKey = &file_fmp_extensions_proto_extTypes[4]
	// optional string unkeyed_model = 51428;
	E_UnkeyedModel = &file_fmp_extensions_proto_extTypes[5]
	// optional bool paginated = 51429;
	E_Paginated = &file_fmp_extensions_proto_extTypes[6]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string child_resource = 51449;
	E_ChildResource = &file_fmp_extensions_proto_extTypes[7]
	// optional string sortable = 51450;
	E_Sortable = &file_fmp_extensions_proto_extTypes[8]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// optional string disable_yang = 51623;
	E_DisableYang = &file_fmp_extensions_proto_extTypes[9]
)

var File_fmp_extensions_proto protoreflect.FileDescriptor

const file_fmp_extensions_proto_rawDesc = "" +
	"\n" +
	"\x14fmp/extensions.proto\x12\x03fmp\x1a google/protobuf/descriptor.proto:7\n" +
	"\x05model\x12\x1f.google.protobuf.MessageOptions\x18ߑ\x03 \x01(\tR\x05model:>\n" +
	"\tmodel_key\x12\x1f.google.protobuf.MessageOptions\x18\xe0\x91\x03 \x01(\bR\bmodelKey:F\n" +
	"\rcustom_filter\x12\x1f.google.protobuf.MessageOptions\x18\xe1\x91\x03 \x01(\tR\fcustomFilter:M\n" +
	"\x11no_default_filter\x12\x1f.google.protobuf.MessageOptions\x18\xe2\x91\x03 \x01(\bR\x0fnoDefaultFilter:I\n" +
	"\x0frequire_set_key\x12\x1f.google.protobuf.MessageOptions\x18\xe3\x91\x03 \x01(\bR\rrequireSetKey:F\n" +
	"\runkeyed_model\x12\x1f.google.protobuf.MessageOptions\x18\xe4\x91\x03 \x01(\tR\funkeyedModel:?\n" +
	"\tpaginated\x12\x1f.google.protobuf.MessageOptions\x18\xe5\x91\x03 \x01(\bR\tpaginated:F\n" +
	"\x0echild_resource\x12\x1d.google.protobuf.FieldOptions\x18\xf9\x91\x03 \x01(\tR\rchildResource:;\n" +
	"\bsortable\x12\x1d.google.protobuf.FieldOptions\x18\xfa\x91\x03 \x01(\tR\bsortable:A\n" +
	"\fdisable_yang\x12\x1c.google.protobuf.FileOptions\x18\xa7\x93\x03 \x01(\tR\vdisableYangB\x81\x01\n" +
	"\acom.fmpB\x0fExtensionsProtoP\x01Z9github.com/ioplane/terraform-provider-cvp/internal/pb/fmp\xa2\x02\x03FXX\xaa\x02\x03Fmp\xca\x02\x03Fmp\xe2\x02\x0fFmp\\GPBMetadata\xea\x02\x03Fmpb\x06proto3"

var file_fmp_extensions_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 1: google.protobuf.FieldOptions
	(*descriptorpb.FileOptions)(nil),    // 2: google.protobuf.FileOptions
}
var file_fmp_extensions_proto_depIdxs = []int32{
	0,  // 0: fmp.model:extendee -> google.protobuf.MessageOptions
	0,  // 1: fmp.model_key:extendee -> google.protobuf.MessageOptions
	0,  // 2: fmp.custom_filter:extendee -> google.protobuf.MessageOptions
	0,  // 3: fmp.no_default_filter:extendee -> google.protobuf.MessageOptions
	0,  // 4: fmp.require_set_key:extendee -> google.protobuf.MessageOptions
	0,  // 5: fmp.unkeyed_model:extendee -> google.protobuf.MessageOptions
	0,  // 6: fmp.paginated:extendee -> google.protobuf.MessageOptions
	1,  // 7: fmp.child_resource:extendee -> google.protobuf.FieldOptions
	1,  // 8: fmp.sortable:extendee -> google.protobuf.FieldOptions
	2,  // 9: fmp.disable_yang:extendee -> google.protobuf.FileOptions
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	0,  // [0:10] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_fmp_extensions_proto_init() }
func file_fmp_extensions_proto_init() {
	if File_fmp_extensions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fmp_extensions_proto_rawDesc), len(file_fmp_extensions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 10,
			NumServices:   0,
		},
		GoTypes:           file_fmp_extensions_proto_goTypes,
		DependencyIndexes: file_fmp_extensions_proto_depIdxs,
		ExtensionInfos:    file_fmp_extensions_proto_extTypes,
	}.Build()
	File_fmp_extensions_proto = out.File
	file_fmp_extensions_proto_goTypes = nil
	file_fmp_extensions_proto_depIdxs = nil
}
