// Copyright (c) 2020 Arista Networks, Inc.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the COPYING file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: arista/time/time.proto

package time

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimeBounds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeBounds) Reset() {
	*x = TimeBounds{}
	mi := &file_arista_time_time_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeBounds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeBounds) ProtoMessage() {}

func (x *TimeBounds) ProtoReflect() protoreflect.Message {
	mi := &file_arista_time_time_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeBounds.ProtoReflect.Descriptor instead.
func (*TimeBounds) Descriptor() ([]byte, []int) {
	return file_arista_time_time_proto_rawDescGZIP(), []int{0}
}

func (x *TimeBounds) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TimeBounds) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

var File_arista_time_time_proto protoreflect.FileDescriptor

const file_arista_time_time_proto_rawDesc = "" +
	"\n" +
	"\x16arista/time/time.proto\x12\varista.time\x1a\x1fgoogle/protobuf/timestamp.proto\"l\n" +
	"\n" +
	"TimeBounds\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03endB\xac\x01\n" +
	"\x0fcom.arista.timeB\tTimeProtoP\x01ZAgithub.com/ioplane/terraform-provider-cvp/internal/pb/arista/time\xa2\x02\x03ATX\xaa\x02\vArista.Time\xca\x02\vArista\\Time\xe2\x02\x17Arista\\Time\\GPBMetadata\xea\x02\fArista::Timeb\x06proto3"

var (
	file_arista_time_time_proto_rawDescOnce sync.Once
	file_arista_time_time_proto_rawDescData []byte
)

func file_arista_time_time_proto_rawDescGZIP() []byte {
	file_arista_time_time_proto_rawDescOnce.Do(func() {
		file_arista_time_time_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arista_time_time_proto_rawDesc), len(file_arista_time_time_proto_rawDesc)))
	})
	return file_arista_time_time_proto_rawDescData
}

var file_arista_time_time_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_arista_time_time_proto_goTypes = []any{
	(*TimeBounds)(nil),            // 0: arista.time.TimeBounds
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_arista_time_time_proto_depIdxs = []int32{
	1, // 0: arista.time.TimeBounds.start:type_name -> google.protobuf.Timestamp
	1, // 1: arista.time.TimeBounds.end:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_arista_time_time_proto_init() }
func file_arista_time_time_proto_init() {
	if File_arista_time_time_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arista_time_time_proto_rawDesc), len(file_arista_time_time_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_arista_time_time_proto_goTypes,
		DependencyIndexes: file_arista_time_time_proto_depIdxs,
		MessageInfos:      file_arista_time_time_proto_msgTypes,
	}.Build()
	File_arista_time_time_proto = out.File
	file_arista_time_time_proto_goTypes = nil
	file_arista_time_time_proto_depIdxs = nil
}
