// Copyright (c) 2023 Arista Networks, Inc.  All rights reserved.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the COPYING file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: arista/imagestatus.v1/imagestatus.proto

package imagestatusv1

import (
	_ "github.com/ioplane/terraform-provider-cvp/internal/pb/fmp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExtensionInstallStatus indicates whether an extension is installed, not installed
// or force installed.
type ExtensionInstallStatus int32

const (
	// EXTENSION_INSTALL_STATUS_UNSPECIFIED indicates extensions install status is unspecified.
	ExtensionInstallStatus_EXTENSION_INSTALL_STATUS_UNSPECIFIED ExtensionInstallStatus = 0
	// EXTENSION_INSTALL_STATUS_NOT_INSTALLED indicates extension is not installed on the device.
	ExtensionInstallStatus_EXTENSION_INSTALL_STATUS_NOT_INSTALLED ExtensionInstallStatus = 1
	// EXTENSION_INSTALL_STATUS_INSTALLED indicates extension is installed on the device.
	ExtensionInstallStatus_EXTENSION_INSTALL_STATUS_INSTALLED ExtensionInstallStatus = 2
	// EXTENSION_INSTALL_STATUS_FORCE_INSTALLED indicates extension is force installed on
	// device.
	ExtensionInstallStatus_EXTENSION_INSTALL_STATUS_FORCE_INSTALLED ExtensionInstallStatus = 3
)

// Enum value maps for ExtensionInstallStatus.
var (
	ExtensionInstallStatus_name = map[int32]string{
		0: "EXTENSION_INSTALL_STATUS_UNSPECIFIED",
		1: "EXTENSION_INSTALL_STATUS_NOT_INSTALLED",
		2: "EXTENSION_INSTALL_STATUS_INSTALLED",
		3: "EXTENSION_INSTALL_STATUS_FORCE_INSTALLED",
	}
	ExtensionInstallStatus_value = map[string]int32{
		"EXTENSION_INSTALL_STATUS_UNSPECIFIED":     0,
		"EXTENSION_INSTALL_STATUS_NOT_INSTALLED":   1,
		"EXTENSION_INSTALL_STATUS_INSTALLED":       2,
		"EXTENSION_INSTALL_STATUS_FORCE_INSTALLED": 3,
	}
)

func (x ExtensionInstallStatus) Enum() *ExtensionInstallStatus {
	p := new(ExtensionInstallStatus)
	*p = x
	return p
}

func (x ExtensionInstallStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExtensionInstallStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_arista_imagestatus_v1_imagestatus_proto_enumTypes[0].Descriptor()
}

func (ExtensionInstallStatus) Type() protoreflect.EnumType {
	return &file_arista_imagestatus_v1_imagestatus_proto_enumTypes[0]
}

func (x ExtensionInstallStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExtensionInstallStatus.Descriptor instead.
func (ExtensionInstallStatus) EnumDescriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{0}
}

// SoftwareComplianceCode indicates possible compliance status.
type SoftwareComplianceCode int32

const (
	// SOFTWARE_COMPLIANCE_CODE_UNSPECIFIED indicates compliance code is unspecified.
	SoftwareComplianceCode_SOFTWARE_COMPLIANCE_CODE_UNSPECIFIED SoftwareComplianceCode = 0
	// SOFTWARE_COMPLIANCE_CODE_IN_SYNC indicates designed and running images/extensions
	// are identical.
	SoftwareComplianceCode_SOFTWARE_COMPLIANCE_CODE_IN_SYNC SoftwareComplianceCode = 1
	// SOFTWARE_COMPLIANCE_CODE_OUT_OF_SYNC indicates designed and running images/extensions
	// are not identical.
	SoftwareComplianceCode_SOFTWARE_COMPLIANCE_CODE_OUT_OF_SYNC SoftwareComplianceCode = 2
)

// Enum value maps for SoftwareComplianceCode.
var (
	SoftwareComplianceCode_name = map[int32]string{
		0: "SOFTWARE_COMPLIANCE_CODE_UNSPECIFIED",
		1: "SOFTWARE_COMPLIANCE_CODE_IN_SYNC",
		2: "SOFTWARE_COMPLIANCE_CODE_OUT_OF_SYNC",
	}
	SoftwareComplianceCode_value = map[string]int32{
		"SOFTWARE_COMPLIANCE_CODE_UNSPECIFIED": 0,
		"SOFTWARE_COMPLIANCE_CODE_IN_SYNC":     1,
		"SOFTWARE_COMPLIANCE_CODE_OUT_OF_SYNC": 2,
	}
)

func (x SoftwareComplianceCode) Enum() *SoftwareComplianceCode {
	p := new(SoftwareComplianceCode)
	*p = x
	return p
}

func (x SoftwareComplianceCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SoftwareComplianceCode) Descriptor() protoreflect.EnumDescriptor {
	return file_arista_imagestatus_v1_imagestatus_proto_enumTypes[1].Descriptor()
}

func (SoftwareComplianceCode) Type() protoreflect.EnumType {
	return &file_arista_imagestatus_v1_imagestatus_proto_enumTypes[1]
}

func (x SoftwareComplianceCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SoftwareComplianceCode.Descriptor instead.
func (SoftwareComplianceCode) EnumDescriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{1}
}

// DiffOp represents the operation performed to get from one side of the diff
// to the other.
type DiffOp int32

const (
	// DIFF_OP_UNSPECIFIED indicates op code is unspecified.
	DiffOp_DIFF_OP_UNSPECIFIED DiffOp = 0
	// DIFF_OP_NOP indicates no change.
	DiffOp_DIFF_OP_NOP DiffOp = 1
	// DIFF_OP_ADD is an addition of a software.
	DiffOp_DIFF_OP_ADD DiffOp = 2
	// DIFF_OP_DELETE is deletion of a software.
	DiffOp_DIFF_OP_DELETE DiffOp = 3
	// DIFF_OP_CHANGE is an update to the software.
	DiffOp_DIFF_OP_CHANGE DiffOp = 4
)

// Enum value maps for DiffOp.
var (
	DiffOp_name = map[int32]string{
		0: "DIFF_OP_UNSPECIFIED",
		1: "DIFF_OP_NOP",
		2: "DIFF_OP_ADD",
		3: "DIFF_OP_DELETE",
		4: "DIFF_OP_CHANGE",
	}
	DiffOp_value = map[string]int32{
		"DIFF_OP_UNSPECIFIED": 0,
		"DIFF_OP_NOP":         1,
		"DIFF_OP_ADD":         2,
		"DIFF_OP_DELETE":      3,
		"DIFF_OP_CHANGE":      4,
	}
)

func (x DiffOp) Enum() *DiffOp {
	p := new(DiffOp)
	*p = x
	return p
}

func (x DiffOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiffOp) Descriptor() protoreflect.EnumDescriptor {
	return file_arista_imagestatus_v1_imagestatus_proto_enumTypes[2].Descriptor()
}

func (DiffOp) Type() protoreflect.EnumType {
	return &file_arista_imagestatus_v1_imagestatus_proto_enumTypes[2]
}

func (x DiffOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiffOp.Descriptor instead.
func (DiffOp) EnumDescriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{2}
}

// ErrorCode indicates errors produced during image validations.
type ErrorCode int32

const (
	// ERROR_CODE_UNSPECIFIED indicates error code is unspecified.
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// ERROR_CODE_SUPPORT_NOT_INTRODUCED represents case where the given EOS version does
	// not support the SKU.
	// Deprecated - use ERROR_CODE_EOS_SUPPORT_NOT_INTRODUCED
	//
	// Deprecated: Marked as deprecated in arista/imagestatus.v1/imagestatus.proto.
	ErrorCode_ERROR_CODE_SUPPORT_NOT_INTRODUCED ErrorCode = 1
	// ERROR_CODE_SUPPORT_REMOVED represents case where the given EOS version no longer
	// supports the SKU.
	// Deprecated - use ERROR_CODE_EOS_SUPPORT_REMOVED
	//
	// Deprecated: Marked as deprecated in arista/imagestatus.v1/imagestatus.proto.
	ErrorCode_ERROR_CODE_SUPPORT_REMOVED ErrorCode = 2
	// ERROR_CODE_DEVICE_UNREACHABLE represents the case where the device
	// is unreachable during a compliance computation.
	ErrorCode_ERROR_CODE_DEVICE_UNREACHABLE ErrorCode = 3
	// ERROR_CODE_VALIDATION_FAILED represents case where the validations checks
	// failed.
	ErrorCode_ERROR_CODE_VALIDATION_FAILED ErrorCode = 4
	// ERROR_CODE_GET_PROPOSED_IMAGE_INFO_FAILED represents case where we are
	// unable to get proposed image information for a device.
	ErrorCode_ERROR_CODE_GET_PROPOSED_IMAGE_INFO_FAILED ErrorCode = 5
	// ERROR_CODE_GET_RUNNING_IMAGE_INFO_FROM_ACTIVE_SUPERVISOR_FAILED represents case where we
	// fail to get running image information from an active supervisor.
	//
	// Deprecated: Marked as deprecated in arista/imagestatus.v1/imagestatus.proto.
	ErrorCode_ERROR_CODE_GET_RUNNING_IMAGE_INFO_FROM_ACTIVE_SUPERVISOR_FAILED ErrorCode = 6
	// ERROR_CODE_GET_RUNNING_IMAGE_INFO_FROM_PEER_SUPERVISOR_FAILED represents case when we
	// fail to get information from peer supervisor.
	//
	// Deprecated: Marked as deprecated in arista/imagestatus.v1/imagestatus.proto.
	ErrorCode_ERROR_CODE_GET_RUNNING_IMAGE_INFO_FROM_PEER_SUPERVISOR_FAILED ErrorCode = 7
	// ERROR_CODE_EOS_TA_ARCHITECTURE_INCOMPATIBLE represents the case where EOS architecture and
	// TerminAttr architecture are incompatible.
	ErrorCode_ERROR_CODE_EOS_TA_ARCHITECTURE_INCOMPATIBLE ErrorCode = 8
	// ERROR_CODE_TA_CV_INCOMPATIBLE represents the case where TerminAttr is too low for CV to
	// support or manage the device.
	ErrorCode_ERROR_CODE_TA_CV_INCOMPATIBLE ErrorCode = 9
	// ERROR_CODE_EOS_CV_INCOMPATIBLE represents the case where EOS is too low for CV to support
	// or manage the device.
	ErrorCode_ERROR_CODE_EOS_CV_INCOMPATIBLE ErrorCode = 10
	// ERROR_CODE_EOS_SUPPORT_NOT_INTRODUCED represents the case where the given EOS version does
	// not support the SKU.
	ErrorCode_ERROR_CODE_EOS_SUPPORT_NOT_INTRODUCED ErrorCode = 11
	// ERROR_CODE_EOS_SUPPORT_REMOVED represents the case where the given EOS version no longer
	// supports the SKU.
	ErrorCode_ERROR_CODE_EOS_SUPPORT_REMOVED ErrorCode = 12
	// ERROR_CODE_PHYSICAL_DEVICE_EOS_INCOMPATIBLE represents the case where the physical device
	// does not support the given EOS type.
	ErrorCode_ERROR_CODE_PHYSICAL_DEVICE_EOS_INCOMPATIBLE ErrorCode = 13
	// ERROR_CODE_TA_EMBEDDEDEXT_INCOMPATIBLE represents the case where the extension TerminAttr
	// version is lower than the embedded TerminAttr version in SWI.
	ErrorCode_ERROR_CODE_TA_EMBEDDEDEXT_INCOMPATIBLE ErrorCode = 14
	// ERROR_CODE_DEVICE_EOS_2GB_INCOMPATIBLE represents the case where a 2GB-device is incompatible
	// with a non-2GB EOS or a non-2GB device is incompatible with a 2GB-EOS.
	ErrorCode_ERROR_CODE_DEVICE_EOS_2GB_INCOMPATIBLE ErrorCode = 15
	// ERROR_CODE_EOS_EXTENSION_VERSION_INCOMPATIBLE represents the case where the given extension
	// version doesn't support the given EOS version.
	ErrorCode_ERROR_CODE_EOS_EXTENSION_VERSION_INCOMPATIBLE ErrorCode = 16
	// ERROR_CODE_ARCH_UNSUPPORTED represents the case where the given image architecture is not
	// supported by CloudVision.
	ErrorCode_ERROR_CODE_ARCH_UNSUPPORTED ErrorCode = 17
	// ERROR_CODE_EOS_EXTENSION_ARCHITECTURE_INCOMPATIBLE represents the case where EOS architecture
	// and Extension architecture are incompatible.
	ErrorCode_ERROR_CODE_EOS_EXTENSION_ARCHITECTURE_INCOMPATIBLE ErrorCode = 18
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_UNSPECIFIED",
		1:  "ERROR_CODE_SUPPORT_NOT_INTRODUCED",
		2:  "ERROR_CODE_SUPPORT_REMOVED",
		3:  "ERROR_CODE_DEVICE_UNREACHABLE",
		4:  "ERROR_CODE_VALIDATION_FAILED",
		5:  "ERROR_CODE_GET_PROPOSED_IMAGE_INFO_FAILED",
		6:  "ERROR_CODE_GET_RUNNING_IMAGE_INFO_FROM_ACTIVE_SUPERVISOR_FAILED",
		7:  "ERROR_CODE_GET_RUNNING_IMAGE_INFO_FROM_PEER_SUPERVISOR_FAILED",
		8:  "ERROR_CODE_EOS_TA_ARCHITECTURE_INCOMPATIBLE",
		9:  "ERROR_CODE_TA_CV_INCOMPATIBLE",
		10: "ERROR_CODE_EOS_CV_INCOMPATIBLE",
		11: "ERROR_CODE_EOS_SUPPORT_NOT_INTRODUCED",
		12: "ERROR_CODE_EOS_SUPPORT_REMOVED",
		13: "ERROR_CODE_PHYSICAL_DEVICE_EOS_INCOMPATIBLE",
		14: "ERROR_CODE_TA_EMBEDDEDEXT_INCOMPATIBLE",
		15: "ERROR_CODE_DEVICE_EOS_2GB_INCOMPATIBLE",
		16: "ERROR_CODE_EOS_EXTENSION_VERSION_INCOMPATIBLE",
		17: "ERROR_CODE_ARCH_UNSUPPORTED",
		18: "ERROR_CODE_EOS_EXTENSION_ARCHITECTURE_INCOMPATIBLE",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":                                          0,
		"ERROR_CODE_SUPPORT_NOT_INTRODUCED":                               1,
		"ERROR_CODE_SUPPORT_REMOVED":                                      2,
		"ERROR_CODE_DEVICE_UNREACHABLE":                                   3,
		"ERROR_CODE_VALIDATION_FAILED":                                    4,
		"ERROR_CODE_GET_PROPOSED_IMAGE_INFO_FAILED":                       5,
		"ERROR_CODE_GET_RUNNING_IMAGE_INFO_FROM_ACTIVE_SUPERVISOR_FAILED": 6,
		"ERROR_CODE_GET_RUNNING_IMAGE_INFO_FROM_PEER_SUPERVISOR_FAILED":   7,
		"ERROR_CODE_EOS_TA_ARCHITECTURE_INCOMPATIBLE":                     8,
		"ERROR_CODE_TA_CV_INCOMPATIBLE":                                   9,
		"ERROR_CODE_EOS_CV_INCOMPATIBLE":                                  10,
		"ERROR_CODE_EOS_SUPPORT_NOT_INTRODUCED":                           11,
		"ERROR_CODE_EOS_SUPPORT_REMOVED":                                  12,
		"ERROR_CODE_PHYSICAL_DEVICE_EOS_INCOMPATIBLE":                     13,
		"ERROR_CODE_TA_EMBEDDEDEXT_INCOMPATIBLE":                          14,
		"ERROR_CODE_DEVICE_EOS_2GB_INCOMPATIBLE":                          15,
		"ERROR_CODE_EOS_EXTENSION_VERSION_INCOMPATIBLE":                   16,
		"ERROR_CODE_ARCH_UNSUPPORTED":                                     17,
		"ERROR_CODE_EOS_EXTENSION_ARCHITECTURE_INCOMPATIBLE":              18,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_arista_imagestatus_v1_imagestatus_proto_enumTypes[3].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_arista_imagestatus_v1_imagestatus_proto_enumTypes[3]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{3}
}

// WarningCode indicates warnings produced during image validations.
type WarningCode int32

const (
	// WARNING_CODE_UNSPECIFIED indicates warning code is unspecified.
	WarningCode_WARNING_CODE_UNSPECIFIED WarningCode = 0
	// WARNING_CODE_NOT_APPLICABLE represents cases where EOS < - > SKU/TA compatibility
	// is not applicable for non physical switches like vEos.
	WarningCode_WARNING_CODE_NOT_APPLICABLE WarningCode = 1
	// WARNING_CODE_SKUINFO_UNAVAILABLE represents case where
	// information about certain skus is missing.
	WarningCode_WARNING_CODE_SKUINFO_UNAVAILABLE WarningCode = 2
	// WARNING_CODE_DEVICE_SKU_UNAVAILABLE represents unavailability of skus for an EOS Device.
	WarningCode_WARNING_CODE_DEVICE_SKU_UNAVAILABLE WarningCode = 3
	// WARNING_CODE_SWI_UNKNOWN represents cases where EOS version is not found in release database.
	WarningCode_WARNING_CODE_SWI_UNKNOWN WarningCode = 4
	// WARNING_CODE_TA_EOS_INCOMPATIBLE represents cases where TA and EOS are not compatible.
	// TA is lower than embedded TA in swi or given TA is unsupported by the EOS.
	WarningCode_WARNING_CODE_TA_EOS_INCOMPATIBLE WarningCode = 5
	// WARNING_CODE_TA_CV_INCOMPATIBLE represents cases where TA is lower than CV's minimum
	// supported version for SMS assignments.
	WarningCode_WARNING_CODE_TA_CV_INCOMPATIBLE WarningCode = 6
	// WARNING_CODE_EOS_CV_INCOMPATIBLE represents the case where EOS is not supported by CV.
	// The given EOS exceeds CV's maximum supported EOS version or for SMS assignments, the given
	// EOS is below CV's minimum supported EOS version.
	WarningCode_WARNING_CODE_EOS_CV_INCOMPATIBLE WarningCode = 7
	// WARNING_CODE_EOS_ARCH_UNKNOWN represents cases where the specified architecture is
	// not valid for EOS.
	WarningCode_WARNING_CODE_EOS_ARCH_UNKNOWN WarningCode = 8
	// WARNING_CODE_TA_EMBEDDEDEXT_INCOMPATIBLE represents cases where TA extension is lower
	// in version than embedded TA in SWI.
	WarningCode_WARNING_CODE_TA_EMBEDDEDEXT_INCOMPATIBLE WarningCode = 9
	// WARNING_CODE_ARCH_INCOMPATIBLE represents cases where EOS arch and TA arch are
	// different. Deprecated.
	//
	// Deprecated: Marked as deprecated in arista/imagestatus.v1/imagestatus.proto.
	WarningCode_WARNING_CODE_ARCH_INCOMPATIBLE WarningCode = 10
	// WARNING_CODE_EOS_END_OF_LIFE_DATE_PASSED represents cases where the given EOS has passed
	// its end of life date.
	WarningCode_WARNING_CODE_EOS_END_OF_LIFE_DATE_PASSED WarningCode = 11
	// WARNING_CODE_SUPPORT_NOT_INTRODUCED represents cases where the given EOS version does
	// not support the SKUs.
	WarningCode_WARNING_CODE_SUPPORT_NOT_INTRODUCED WarningCode = 12
	// WARNING_CODE_SUPPORT_REMOVED represents cases where the given EOS version no longer
	// supports the SKUs.
	WarningCode_WARNING_CODE_SUPPORT_REMOVED WarningCode = 13
	// WARNING_CODE_RUNNING_TA_BELOW_MIN_SUPPORTED_VERSION represents cases where the running
	// TerminAttr version is below CloudVision's minimum supported version.
	WarningCode_WARNING_CODE_RUNNING_TA_BELOW_MIN_SUPPORTED_VERSION WarningCode = 14
	// WARNING_CODE_TA_STUDIO_INCOMPATIBLE represents cases where the TerminAttr is incompatible
	// with Software Management Studio.
	WarningCode_WARNING_CODE_TA_STUDIO_INCOMPATIBLE WarningCode = 15
	// WARNING_CODE_BUGALERTS_DATA_MISSING represents cases where some of the BugAlerts data
	// under Aeris analytics dataset is missing.
	WarningCode_WARNING_CODE_BUGALERTS_DATA_MISSING WarningCode = 16
)

// Enum value maps for WarningCode.
var (
	WarningCode_name = map[int32]string{
		0:  "WARNING_CODE_UNSPECIFIED",
		1:  "WARNING_CODE_NOT_APPLICABLE",
		2:  "WARNING_CODE_SKUINFO_UNAVAILABLE",
		3:  "WARNING_CODE_DEVICE_SKU_UNAVAILABLE",
		4:  "WARNING_CODE_SWI_UNKNOWN",
		5:  "WARNING_CODE_TA_EOS_INCOMPATIBLE",
		6:  "WARNING_CODE_TA_CV_INCOMPATIBLE",
		7:  "WARNING_CODE_EOS_CV_INCOMPATIBLE",
		8:  "WARNING_CODE_EOS_ARCH_UNKNOWN",
		9:  "WARNING_CODE_TA_EMBEDDEDEXT_INCOMPATIBLE",
		10: "WARNING_CODE_ARCH_INCOMPATIBLE",
		11: "WARNING_CODE_EOS_END_OF_LIFE_DATE_PASSED",
		12: "WARNING_CODE_SUPPORT_NOT_INTRODUCED",
		13: "WARNING_CODE_SUPPORT_REMOVED",
		14: "WARNING_CODE_RUNNING_TA_BELOW_MIN_SUPPORTED_VERSION",
		15: "WARNING_CODE_TA_STUDIO_INCOMPATIBLE",
		16: "WARNING_CODE_BUGALERTS_DATA_MISSING",
	}
	WarningCode_value = map[string]int32{
		"WARNING_CODE_UNSPECIFIED":                            0,
		"WARNING_CODE_NOT_APPLICABLE":                         1,
		"WARNING_CODE_SKUINFO_UNAVAILABLE":                    2,
		"WARNING_CODE_DEVICE_SKU_UNAVAILABLE":                 3,
		"WARNING_CODE_SWI_UNKNOWN":                            4,
		"WARNING_CODE_TA_EOS_INCOMPATIBLE":                    5,
		"WARNING_CODE_TA_CV_INCOMPATIBLE":                     6,
		"WARNING_CODE_EOS_CV_INCOMPATIBLE":                    7,
		"WARNING_CODE_EOS_ARCH_UNKNOWN":                       8,
		"WARNING_CODE_TA_EMBEDDEDEXT_INCOMPATIBLE":            9,
		"WARNING_CODE_ARCH_INCOMPATIBLE":                      10,
		"WARNING_CODE_EOS_END_OF_LIFE_DATE_PASSED":            11,
		"WARNING_CODE_SUPPORT_NOT_INTRODUCED":                 12,
		"WARNING_CODE_SUPPORT_REMOVED":                        13,
		"WARNING_CODE_RUNNING_TA_BELOW_MIN_SUPPORTED_VERSION": 14,
		"WARNING_CODE_TA_STUDIO_INCOMPATIBLE":                 15,
		"WARNING_CODE_BUGALERTS_DATA_MISSING":                 16,
	}
)

func (x WarningCode) Enum() *WarningCode {
	p := new(WarningCode)
	*p = x
	return p
}

func (x WarningCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WarningCode) Descriptor() protoreflect.EnumDescriptor {
	return file_arista_imagestatus_v1_imagestatus_proto_enumTypes[4].Descriptor()
}

func (WarningCode) Type() protoreflect.EnumType {
	return &file_arista_imagestatus_v1_imagestatus_proto_enumTypes[4]
}

func (x WarningCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WarningCode.Descriptor instead.
func (WarningCode) EnumDescriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{4}
}

// InfoCode indicates info messages produced during image validations.
type InfoCode int32

const (
	// INFO_CODE_UNSPECIFIED indicates info code is unspecified.
	InfoCode_INFO_CODE_UNSPECIFIED InfoCode = 0
	// INFO_CODE_NEWER_VERSION_AVAILABLE represents cases where a newer EOS maintainance
	// release is available for download.
	InfoCode_INFO_CODE_NEWER_VERSION_AVAILABLE InfoCode = 1
	// INFO_CODE_UNIVERSAL_IMAGE_ARCH_APPLIED represents cases where a specific architecture is
	// picked for a Universal (multiarch) EOS image.
	InfoCode_INFO_CODE_UNIVERSAL_IMAGE_ARCH_APPLIED InfoCode = 2
)

// Enum value maps for InfoCode.
var (
	InfoCode_name = map[int32]string{
		0: "INFO_CODE_UNSPECIFIED",
		1: "INFO_CODE_NEWER_VERSION_AVAILABLE",
		2: "INFO_CODE_UNIVERSAL_IMAGE_ARCH_APPLIED",
	}
	InfoCode_value = map[string]int32{
		"INFO_CODE_UNSPECIFIED":                  0,
		"INFO_CODE_NEWER_VERSION_AVAILABLE":      1,
		"INFO_CODE_UNIVERSAL_IMAGE_ARCH_APPLIED": 2,
	}
)

func (x InfoCode) Enum() *InfoCode {
	p := new(InfoCode)
	*p = x
	return p
}

func (x InfoCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InfoCode) Descriptor() protoreflect.EnumDescriptor {
	return file_arista_imagestatus_v1_imagestatus_proto_enumTypes[5].Descriptor()
}

func (InfoCode) Type() protoreflect.EnumType {
	return &file_arista_imagestatus_v1_imagestatus_proto_enumTypes[5]
}

func (x InfoCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InfoCode.Descriptor instead.
func (InfoCode) EnumDescriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{5}
}

// ImageSource indicates the source type for the image configuration.
type ImageSource int32

const (
	// IMAGE_SOURCE_UNSPECIFIED uninitialized value
	ImageSource_IMAGE_SOURCE_UNSPECIFIED ImageSource = 0
	// IMAGE_SOURCE_STUDIO - image configured from studio
	ImageSource_IMAGE_SOURCE_STUDIO ImageSource = 1
	// IMAGE_SOURCE_NETWORK_PROVISIONING - image configured from
	// network provisioning workflow
	ImageSource_IMAGE_SOURCE_NETWORK_PROVISIONING ImageSource = 2
	// IMAGE_SOURCE_HIERARCHY - image configured from hierarchy workflow
	ImageSource_IMAGE_SOURCE_HIERARCHY ImageSource = 3
)

// Enum value maps for ImageSource.
var (
	ImageSource_name = map[int32]string{
		0: "IMAGE_SOURCE_UNSPECIFIED",
		1: "IMAGE_SOURCE_STUDIO",
		2: "IMAGE_SOURCE_NETWORK_PROVISIONING",
		3: "IMAGE_SOURCE_HIERARCHY",
	}
	ImageSource_value = map[string]int32{
		"IMAGE_SOURCE_UNSPECIFIED":          0,
		"IMAGE_SOURCE_STUDIO":               1,
		"IMAGE_SOURCE_NETWORK_PROVISIONING": 2,
		"IMAGE_SOURCE_HIERARCHY":            3,
	}
)

func (x ImageSource) Enum() *ImageSource {
	p := new(ImageSource)
	*p = x
	return p
}

func (x ImageSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageSource) Descriptor() protoreflect.EnumDescriptor {
	return file_arista_imagestatus_v1_imagestatus_proto_enumTypes[6].Descriptor()
}

func (ImageSource) Type() protoreflect.EnumType {
	return &file_arista_imagestatus_v1_imagestatus_proto_enumTypes[6]
}

func (x ImageSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageSource.Descriptor instead.
func (ImageSource) EnumDescriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{6}
}

// SoftwareImage provides information of the running/designed EOS image.
type SoftwareImage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the name of the EOS image.
	Name *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version is the version of the EOS image.
	Version *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// metadata  is the metadata of EOS image.
	Metadata      *ImageMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoftwareImage) Reset() {
	*x = SoftwareImage{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftwareImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftwareImage) ProtoMessage() {}

func (x *SoftwareImage) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftwareImage.ProtoReflect.Descriptor instead.
func (*SoftwareImage) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{0}
}

func (x *SoftwareImage) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *SoftwareImage) GetVersion() *wrapperspb.StringValue {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *SoftwareImage) GetMetadata() *ImageMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ImageMetadata provides information regarding the software image.
type ImageMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// version is the version of the EOS image.
	Version *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// release is the release name of the EOS image.
	Release *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=release,proto3" json:"release,omitempty"`
	// flavor is the flavor information of the EOS image.
	// default flavor is DEFAULT. Other flavors can be DPE, 2GB, etc.
	Flavor *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=flavor,proto3" json:"flavor,omitempty"`
	// variant is the variant information of the EOS image.
	// possible values: INT or US.
	Variant *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=variant,proto3" json:"variant,omitempty"`
	// arch is the architecture of the EOS image.
	Arch          *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageMetadata) Reset() {
	*x = ImageMetadata{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageMetadata) ProtoMessage() {}

func (x *ImageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageMetadata.ProtoReflect.Descriptor instead.
func (*ImageMetadata) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{1}
}

func (x *ImageMetadata) GetVersion() *wrapperspb.StringValue {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ImageMetadata) GetRelease() *wrapperspb.StringValue {
	if x != nil {
		return x.Release
	}
	return nil
}

func (x *ImageMetadata) GetFlavor() *wrapperspb.StringValue {
	if x != nil {
		return x.Flavor
	}
	return nil
}

func (x *ImageMetadata) GetVariant() *wrapperspb.StringValue {
	if x != nil {
		return x.Variant
	}
	return nil
}

func (x *ImageMetadata) GetArch() *wrapperspb.StringValue {
	if x != nil {
		return x.Arch
	}
	return nil
}

// Extension provides information of the running/designed extensions.
type Extension struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the name of the extension.
	Name *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version is the version of the extension.
	Version *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// reboot_required indicates whether applying/deleting this extension
	// would result in a reboot.
	RebootRequired *wrapperspb.BoolValue `protobuf:"bytes,3,opt,name=reboot_required,json=rebootRequired,proto3" json:"reboot_required,omitempty"`
	// present indicates whether the extension is present in the device
	// or not.
	Present *wrapperspb.BoolValue `protobuf:"bytes,4,opt,name=present,proto3" json:"present,omitempty"`
	// installed indicates whether the extension is installed, not
	// installed or force installed.
	Installed ExtensionInstallStatus `protobuf:"varint,5,opt,name=installed,proto3,enum=arista.imagestatus.v1.ExtensionInstallStatus" json:"installed,omitempty"`
	// status_detail gives the details behind installation of the extension.
	StatusDetail *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=status_detail,json=statusDetail,proto3" json:"status_detail,omitempty"`
	// is_embedded indicates whether the extension is embedded in the EOS swi
	// or not.
	IsEmbedded *wrapperspb.BoolValue `protobuf:"bytes,7,opt,name=is_embedded,json=isEmbedded,proto3" json:"is_embedded,omitempty"`
	// arch is architecture type of the extension.
	Arch          *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Extension) Reset() {
	*x = Extension{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extension) ProtoMessage() {}

func (x *Extension) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extension.ProtoReflect.Descriptor instead.
func (*Extension) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{2}
}

func (x *Extension) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Extension) GetVersion() *wrapperspb.StringValue {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *Extension) GetRebootRequired() *wrapperspb.BoolValue {
	if x != nil {
		return x.RebootRequired
	}
	return nil
}

func (x *Extension) GetPresent() *wrapperspb.BoolValue {
	if x != nil {
		return x.Present
	}
	return nil
}

func (x *Extension) GetInstalled() ExtensionInstallStatus {
	if x != nil {
		return x.Installed
	}
	return ExtensionInstallStatus_EXTENSION_INSTALL_STATUS_UNSPECIFIED
}

func (x *Extension) GetStatusDetail() *wrapperspb.StringValue {
	if x != nil {
		return x.StatusDetail
	}
	return nil
}

func (x *Extension) GetIsEmbedded() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsEmbedded
	}
	return nil
}

func (x *Extension) GetArch() *wrapperspb.StringValue {
	if x != nil {
		return x.Arch
	}
	return nil
}

// Extensions provides an ordered list of running/designed extensions.
type Extensions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// values represents extension information.
	Values        []*Extension `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Extensions) Reset() {
	*x = Extensions{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extensions) ProtoMessage() {}

func (x *Extensions) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extensions.ProtoReflect.Descriptor instead.
func (*Extensions) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{3}
}

func (x *Extensions) GetValues() []*Extension {
	if x != nil {
		return x.Values
	}
	return nil
}

// ComplianceStatus indicates compliance status for software image, terminattr
// and extensions.
type ComplianceStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// software_image_compliance_code is the compliance code for images.
	SoftwareImageComplianceCode SoftwareComplianceCode `protobuf:"varint,1,opt,name=software_image_compliance_code,json=softwareImageComplianceCode,proto3,enum=arista.imagestatus.v1.SoftwareComplianceCode" json:"software_image_compliance_code,omitempty"`
	// terminattr_compliance_code is the compliance code for TerminAttr.
	TerminattrComplianceCode SoftwareComplianceCode `protobuf:"varint,2,opt,name=terminattr_compliance_code,json=terminattrComplianceCode,proto3,enum=arista.imagestatus.v1.SoftwareComplianceCode" json:"terminattr_compliance_code,omitempty"`
	// extensions_compliance_code is the compliance code for extensions.
	ExtensionsComplianceCode SoftwareComplianceCode `protobuf:"varint,3,opt,name=extensions_compliance_code,json=extensionsComplianceCode,proto3,enum=arista.imagestatus.v1.SoftwareComplianceCode" json:"extensions_compliance_code,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ComplianceStatus) Reset() {
	*x = ComplianceStatus{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplianceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplianceStatus) ProtoMessage() {}

func (x *ComplianceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplianceStatus.ProtoReflect.Descriptor instead.
func (*ComplianceStatus) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{4}
}

func (x *ComplianceStatus) GetSoftwareImageComplianceCode() SoftwareComplianceCode {
	if x != nil {
		return x.SoftwareImageComplianceCode
	}
	return SoftwareComplianceCode_SOFTWARE_COMPLIANCE_CODE_UNSPECIFIED
}

func (x *ComplianceStatus) GetTerminattrComplianceCode() SoftwareComplianceCode {
	if x != nil {
		return x.TerminattrComplianceCode
	}
	return SoftwareComplianceCode_SOFTWARE_COMPLIANCE_CODE_UNSPECIFIED
}

func (x *ComplianceStatus) GetExtensionsComplianceCode() SoftwareComplianceCode {
	if x != nil {
		return x.ExtensionsComplianceCode
	}
	return SoftwareComplianceCode_SOFTWARE_COMPLIANCE_CODE_UNSPECIFIED
}

// ComplianceStatusBySup is a map that indicates the compliance code for each
// supervisor.
type ComplianceStatusBySup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// values is the mapping of supervisor type to compliance code.
	Values        map[string]*ComplianceStatus `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplianceStatusBySup) Reset() {
	*x = ComplianceStatusBySup{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplianceStatusBySup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplianceStatusBySup) ProtoMessage() {}

func (x *ComplianceStatusBySup) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplianceStatusBySup.ProtoReflect.Descriptor instead.
func (*ComplianceStatusBySup) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{5}
}

func (x *ComplianceStatusBySup) GetValues() map[string]*ComplianceStatus {
	if x != nil {
		return x.Values
	}
	return nil
}

// RebootRequired indicates the reboot information per software image,
// terminattr and extension for the switch as a whole.
type RebootRequired struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// software_image_reboot_required indicates whether reboot is required
	// for the software image being applied.
	SoftwareImageRebootRequired *wrapperspb.BoolValue `protobuf:"bytes,1,opt,name=software_image_reboot_required,json=softwareImageRebootRequired,proto3" json:"software_image_reboot_required,omitempty"`
	// terminattr_reboot_required indicates whether reboot is required
	// for the terminattr being applied/deleted.
	TerminattrRebootRequired *wrapperspb.BoolValue `protobuf:"bytes,2,opt,name=terminattr_reboot_required,json=terminattrRebootRequired,proto3" json:"terminattr_reboot_required,omitempty"`
	// extension_reboot_required indicates whether reboot is required
	// for the extensions being applied/deleted.
	ExtensionRebootRequired *wrapperspb.BoolValue `protobuf:"bytes,3,opt,name=extension_reboot_required,json=extensionRebootRequired,proto3" json:"extension_reboot_required,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RebootRequired) Reset() {
	*x = RebootRequired{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootRequired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootRequired) ProtoMessage() {}

func (x *RebootRequired) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootRequired.ProtoReflect.Descriptor instead.
func (*RebootRequired) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{6}
}

func (x *RebootRequired) GetSoftwareImageRebootRequired() *wrapperspb.BoolValue {
	if x != nil {
		return x.SoftwareImageRebootRequired
	}
	return nil
}

func (x *RebootRequired) GetTerminattrRebootRequired() *wrapperspb.BoolValue {
	if x != nil {
		return x.TerminattrRebootRequired
	}
	return nil
}

func (x *RebootRequired) GetExtensionRebootRequired() *wrapperspb.BoolValue {
	if x != nil {
		return x.ExtensionRebootRequired
	}
	return nil
}

// SoftwareImageDiff is the diff for the running/designed images.
type SoftwareImageDiff struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code indicates the operation performed to get from one side of the diff
	// to the other.
	Code DiffOp `protobuf:"varint,1,opt,name=code,proto3,enum=arista.imagestatus.v1.DiffOp" json:"code,omitempty"`
	// a is the software image on the a side (left hand side).
	A *SoftwareImage `protobuf:"bytes,2,opt,name=a,proto3" json:"a,omitempty"`
	// b is the software image on the b side (right hand side).
	B *SoftwareImage `protobuf:"bytes,3,opt,name=b,proto3" json:"b,omitempty"`
	// text_code is the color in the diff view page.
	TextCode      DiffOp `protobuf:"varint,4,opt,name=text_code,json=textCode,proto3,enum=arista.imagestatus.v1.DiffOp" json:"text_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoftwareImageDiff) Reset() {
	*x = SoftwareImageDiff{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftwareImageDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftwareImageDiff) ProtoMessage() {}

func (x *SoftwareImageDiff) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftwareImageDiff.ProtoReflect.Descriptor instead.
func (*SoftwareImageDiff) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{7}
}

func (x *SoftwareImageDiff) GetCode() DiffOp {
	if x != nil {
		return x.Code
	}
	return DiffOp_DIFF_OP_UNSPECIFIED
}

func (x *SoftwareImageDiff) GetA() *SoftwareImage {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *SoftwareImageDiff) GetB() *SoftwareImage {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *SoftwareImageDiff) GetTextCode() DiffOp {
	if x != nil {
		return x.TextCode
	}
	return DiffOp_DIFF_OP_UNSPECIFIED
}

// SoftwareImageDiffsBySup is software image diff information for each
// supervisor.
type SoftwareImageDiffsBySup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// values is the mapping of supervisor type to image diff.
	Values        map[string]*SoftwareImageDiff `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoftwareImageDiffsBySup) Reset() {
	*x = SoftwareImageDiffsBySup{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftwareImageDiffsBySup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftwareImageDiffsBySup) ProtoMessage() {}

func (x *SoftwareImageDiffsBySup) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftwareImageDiffsBySup.ProtoReflect.Descriptor instead.
func (*SoftwareImageDiffsBySup) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{8}
}

func (x *SoftwareImageDiffsBySup) GetValues() map[string]*SoftwareImageDiff {
	if x != nil {
		return x.Values
	}
	return nil
}

// ExtensionDiff is the diff for the running/designed extensions.
type ExtensionDiff struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code indicates the operation performed to get from one side of the diff
	// to the other.
	Code DiffOp `protobuf:"varint,1,opt,name=code,proto3,enum=arista.imagestatus.v1.DiffOp" json:"code,omitempty"`
	// a is the extension on the a side (left hand side).
	A *Extension `protobuf:"bytes,2,opt,name=a,proto3" json:"a,omitempty"`
	// b is the extension on the b side (right hand side).
	B *Extension `protobuf:"bytes,3,opt,name=b,proto3" json:"b,omitempty"`
	// text_code is the color in the diff view page.
	TextCode      DiffOp `protobuf:"varint,4,opt,name=text_code,json=textCode,proto3,enum=arista.imagestatus.v1.DiffOp" json:"text_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionDiff) Reset() {
	*x = ExtensionDiff{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionDiff) ProtoMessage() {}

func (x *ExtensionDiff) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionDiff.ProtoReflect.Descriptor instead.
func (*ExtensionDiff) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{9}
}

func (x *ExtensionDiff) GetCode() DiffOp {
	if x != nil {
		return x.Code
	}
	return DiffOp_DIFF_OP_UNSPECIFIED
}

func (x *ExtensionDiff) GetA() *Extension {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *ExtensionDiff) GetB() *Extension {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *ExtensionDiff) GetTextCode() DiffOp {
	if x != nil {
		return x.TextCode
	}
	return DiffOp_DIFF_OP_UNSPECIFIED
}

// TerminAttrDiffsBySup is the terminattr diff information for each supervisor.
type TerminAttrDiffsBySup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// values is the mapping of supervisor type to terminattr diff.
	Values        map[string]*ExtensionDiff `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminAttrDiffsBySup) Reset() {
	*x = TerminAttrDiffsBySup{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminAttrDiffsBySup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminAttrDiffsBySup) ProtoMessage() {}

func (x *TerminAttrDiffsBySup) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminAttrDiffsBySup.ProtoReflect.Descriptor instead.
func (*TerminAttrDiffsBySup) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{10}
}

func (x *TerminAttrDiffsBySup) GetValues() map[string]*ExtensionDiff {
	if x != nil {
		return x.Values
	}
	return nil
}

// ExtensionDiffs is a list of extension diff information in the order they
// will be applied.
type ExtensionDiffs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// values is an ordered list of extension diffs applied to the device.
	Values        []*ExtensionDiff `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionDiffs) Reset() {
	*x = ExtensionDiffs{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionDiffs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionDiffs) ProtoMessage() {}

func (x *ExtensionDiffs) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionDiffs.ProtoReflect.Descriptor instead.
func (*ExtensionDiffs) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{11}
}

func (x *ExtensionDiffs) GetValues() []*ExtensionDiff {
	if x != nil {
		return x.Values
	}
	return nil
}

// ExtensionDiffsBySup is the extension diff information for each supervisor.
type ExtensionDiffsBySup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// values is the mapping of supervisor type to extension diff.
	Values        map[string]*ExtensionDiffs `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionDiffsBySup) Reset() {
	*x = ExtensionDiffsBySup{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionDiffsBySup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionDiffsBySup) ProtoMessage() {}

func (x *ExtensionDiffsBySup) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionDiffsBySup.ProtoReflect.Descriptor instead.
func (*ExtensionDiffsBySup) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{12}
}

func (x *ExtensionDiffsBySup) GetValues() map[string]*ExtensionDiffs {
	if x != nil {
		return x.Values
	}
	return nil
}

// ImageSummary represents device image summary.
type ImageSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sku indicates the top-level sku or model number.
	Sku *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	// running_image_update_time is the most recent timestamp at which one of
	// running image side properties is updated.
	RunningImageUpdateTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=running_image_update_time,json=runningImageUpdateTime,proto3" json:"running_image_update_time,omitempty"`
	// designed_image_update_time is the most recent timestamp at which one of
	// designed image side properties is updated.
	DesignedImageUpdateTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=designed_image_update_time,json=designedImageUpdateTime,proto3" json:"designed_image_update_time,omitempty"`
	// dual_sup indicates if a device is a dual supervisor.
	DualSup *wrapperspb.BoolValue `protobuf:"bytes,4,opt,name=dual_sup,json=dualSup,proto3" json:"dual_sup,omitempty"`
	// active_slot indicates the physical slot number for the the active
	// supervisor.
	ActiveSlot *wrapperspb.Int32Value `protobuf:"bytes,5,opt,name=active_slot,json=activeSlot,proto3" json:"active_slot,omitempty"`
	// standby_slot indicates the physical slot number for the standby
	// supervisor.
	StandbySlot *wrapperspb.Int32Value `protobuf:"bytes,6,opt,name=standby_slot,json=standbySlot,proto3" json:"standby_slot,omitempty"`
	// software_image_diff indicates the image diff for each supervisor.
	SoftwareImageDiff *SoftwareImageDiffsBySup `protobuf:"bytes,7,opt,name=software_image_diff,json=softwareImageDiff,proto3" json:"software_image_diff,omitempty"`
	// terminattr_diff indicates the terminattr diff for each supervisor.
	TerminattrDiff *TerminAttrDiffsBySup `protobuf:"bytes,8,opt,name=terminattr_diff,json=terminattrDiff,proto3" json:"terminattr_diff,omitempty"`
	// extensions_diff indicates the extension diff for each supervisor.
	ExtensionsDiff *ExtensionDiffsBySup `protobuf:"bytes,9,opt,name=extensions_diff,json=extensionsDiff,proto3" json:"extensions_diff,omitempty"`
	// compliance_status is the aggregated compliance status (including both
	// active/standby and image/TA/extension compliance).
	ComplianceStatus SoftwareComplianceCode `protobuf:"varint,10,opt,name=compliance_status,json=complianceStatus,proto3,enum=arista.imagestatus.v1.SoftwareComplianceCode" json:"compliance_status,omitempty"`
	// compliance provides compliance information for each supervisor.
	Compliance *ComplianceStatusBySup `protobuf:"bytes,11,opt,name=compliance,proto3" json:"compliance,omitempty"`
	// reboot_required indicates whether a reboot is required if the designed
	// image is pushed to the device.
	RebootRequired *RebootRequired `protobuf:"bytes,12,opt,name=reboot_required,json=rebootRequired,proto3" json:"reboot_required,omitempty"`
	// digest is the digest of the image summary. It can use SHA-256 hash
	// algorithm for example. It is computed by stringifying the
	// software_image_diff, terminattr_diff and extensions_diff and computing the
	// hash.
	Digest        *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageSummary) Reset() {
	*x = ImageSummary{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSummary) ProtoMessage() {}

func (x *ImageSummary) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSummary.ProtoReflect.Descriptor instead.
func (*ImageSummary) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{13}
}

func (x *ImageSummary) GetSku() *wrapperspb.StringValue {
	if x != nil {
		return x.Sku
	}
	return nil
}

func (x *ImageSummary) GetRunningImageUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RunningImageUpdateTime
	}
	return nil
}

func (x *ImageSummary) GetDesignedImageUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DesignedImageUpdateTime
	}
	return nil
}

func (x *ImageSummary) GetDualSup() *wrapperspb.BoolValue {
	if x != nil {
		return x.DualSup
	}
	return nil
}

func (x *ImageSummary) GetActiveSlot() *wrapperspb.Int32Value {
	if x != nil {
		return x.ActiveSlot
	}
	return nil
}

func (x *ImageSummary) GetStandbySlot() *wrapperspb.Int32Value {
	if x != nil {
		return x.StandbySlot
	}
	return nil
}

func (x *ImageSummary) GetSoftwareImageDiff() *SoftwareImageDiffsBySup {
	if x != nil {
		return x.SoftwareImageDiff
	}
	return nil
}

func (x *ImageSummary) GetTerminattrDiff() *TerminAttrDiffsBySup {
	if x != nil {
		return x.TerminattrDiff
	}
	return nil
}

func (x *ImageSummary) GetExtensionsDiff() *ExtensionDiffsBySup {
	if x != nil {
		return x.ExtensionsDiff
	}
	return nil
}

func (x *ImageSummary) GetComplianceStatus() SoftwareComplianceCode {
	if x != nil {
		return x.ComplianceStatus
	}
	return SoftwareComplianceCode_SOFTWARE_COMPLIANCE_CODE_UNSPECIFIED
}

func (x *ImageSummary) GetCompliance() *ComplianceStatusBySup {
	if x != nil {
		return x.Compliance
	}
	return nil
}

func (x *ImageSummary) GetRebootRequired() *RebootRequired {
	if x != nil {
		return x.RebootRequired
	}
	return nil
}

func (x *ImageSummary) GetDigest() *wrapperspb.StringValue {
	if x != nil {
		return x.Digest
	}
	return nil
}

// SummaryKey uniquely identifies a device summary request.
type SummaryKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device_id is the serial number of the device
	DeviceId      *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryKey) Reset() {
	*x = SummaryKey{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryKey) ProtoMessage() {}

func (x *SummaryKey) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryKey.ProtoReflect.Descriptor instead.
func (*SummaryKey) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{14}
}

func (x *SummaryKey) GetDeviceId() *wrapperspb.StringValue {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

// Summary represents the device image summary.
type Summary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key represents the image summary key.
	Key *SummaryKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// summary is the image diff summary.
	Summary *ImageSummary `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	// errors are the image errors encountered while validating the image. These are
	// displayed on the workspace build results page.
	Errors *ImageErrors `protobuf:"bytes,3,opt,name=errors,proto3" json:"errors,omitempty"`
	// warnings are the image warnings encountered while validating the image. These are
	// displayed on the workspace build results page.
	Warnings *ImageWarnings `protobuf:"bytes,4,opt,name=warnings,proto3" json:"warnings,omitempty"`
	// infos are the image infos encountered while validating the image. These are
	// displayed on the workspace build results page.
	Infos         *ImageInfos `protobuf:"bytes,5,opt,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{15}
}

func (x *Summary) GetKey() *SummaryKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Summary) GetSummary() *ImageSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *Summary) GetErrors() *ImageErrors {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *Summary) GetWarnings() *ImageWarnings {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *Summary) GetInfos() *ImageInfos {
	if x != nil {
		return x.Infos
	}
	return nil
}

// ImageError wraps `ErrorCode` enum with a reason string.
type ImageError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sku represents the name of the sku.
	Sku *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	// error_code is the error code.
	ErrorCode ErrorCode `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=arista.imagestatus.v1.ErrorCode" json:"error_code,omitempty"`
	// error_msg provides a description of the error.
	ErrorMsg      *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageError) Reset() {
	*x = ImageError{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageError) ProtoMessage() {}

func (x *ImageError) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageError.ProtoReflect.Descriptor instead.
func (*ImageError) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{16}
}

func (x *ImageError) GetSku() *wrapperspb.StringValue {
	if x != nil {
		return x.Sku
	}
	return nil
}

func (x *ImageError) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ImageError) GetErrorMsg() *wrapperspb.StringValue {
	if x != nil {
		return x.ErrorMsg
	}
	return nil
}

// ImageErrors is the list of errors reported by CVP when handling image
// validations.
type ImageErrors struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// values is a list of image errors.
	Values        []*ImageError `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageErrors) Reset() {
	*x = ImageErrors{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageErrors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageErrors) ProtoMessage() {}

func (x *ImageErrors) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageErrors.ProtoReflect.Descriptor instead.
func (*ImageErrors) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{17}
}

func (x *ImageErrors) GetValues() []*ImageError {
	if x != nil {
		return x.Values
	}
	return nil
}

// ImageWarning wraps `WarningCode` enum with a reason string.
type ImageWarning struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sku represents the name of the sku.
	Sku *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	// warning_code is the warning code.
	WarningCode WarningCode `protobuf:"varint,2,opt,name=warning_code,json=warningCode,proto3,enum=arista.imagestatus.v1.WarningCode" json:"warning_code,omitempty"`
	// warning_msg provides a description of the warning.
	WarningMsg    *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=warning_msg,json=warningMsg,proto3" json:"warning_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageWarning) Reset() {
	*x = ImageWarning{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageWarning) ProtoMessage() {}

func (x *ImageWarning) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageWarning.ProtoReflect.Descriptor instead.
func (*ImageWarning) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{18}
}

func (x *ImageWarning) GetSku() *wrapperspb.StringValue {
	if x != nil {
		return x.Sku
	}
	return nil
}

func (x *ImageWarning) GetWarningCode() WarningCode {
	if x != nil {
		return x.WarningCode
	}
	return WarningCode_WARNING_CODE_UNSPECIFIED
}

func (x *ImageWarning) GetWarningMsg() *wrapperspb.StringValue {
	if x != nil {
		return x.WarningMsg
	}
	return nil
}

// ImageWarnings is the list of warnings reported by CVP when handling image
// validations.
type ImageWarnings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// values is a list of image warnings.
	Values        []*ImageWarning `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageWarnings) Reset() {
	*x = ImageWarnings{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageWarnings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageWarnings) ProtoMessage() {}

func (x *ImageWarnings) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageWarnings.ProtoReflect.Descriptor instead.
func (*ImageWarnings) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{19}
}

func (x *ImageWarnings) GetValues() []*ImageWarning {
	if x != nil {
		return x.Values
	}
	return nil
}

// ImageInfo wraps `InfoCode` enum with a reason string.
type ImageInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sku represents the name of the sku.
	Sku *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	// info_code is the info code.
	InfoCode InfoCode `protobuf:"varint,2,opt,name=info_code,json=infoCode,proto3,enum=arista.imagestatus.v1.InfoCode" json:"info_code,omitempty"`
	// info_msg provides a description of the info.
	InfoMsg       *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=info_msg,json=infoMsg,proto3" json:"info_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{20}
}

func (x *ImageInfo) GetSku() *wrapperspb.StringValue {
	if x != nil {
		return x.Sku
	}
	return nil
}

func (x *ImageInfo) GetInfoCode() InfoCode {
	if x != nil {
		return x.InfoCode
	}
	return InfoCode_INFO_CODE_UNSPECIFIED
}

func (x *ImageInfo) GetInfoMsg() *wrapperspb.StringValue {
	if x != nil {
		return x.InfoMsg
	}
	return nil
}

// ImageInfos is the list of info messages reported by CVP when handling image validations.
type ImageInfos struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// values is a list of image infos.
	Values        []*ImageInfo `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfos) Reset() {
	*x = ImageInfos{}
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfos) ProtoMessage() {}

func (x *ImageInfos) ProtoReflect() protoreflect.Message {
	mi := &file_arista_imagestatus_v1_imagestatus_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfos.ProtoReflect.Descriptor instead.
func (*ImageInfos) Descriptor() ([]byte, []int) {
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP(), []int{21}
}

func (x *ImageInfos) GetValues() []*ImageInfo {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_arista_imagestatus_v1_imagestatus_proto protoreflect.FileDescriptor

const file_arista_imagestatus_v1_imagestatus_proto_rawDesc = "" +
	"\n" +
	"'arista/imagestatus.v1/imagestatus.proto\x12\x15arista.imagestatus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x14fmp/extensions.proto\"\xbb\x01\n" +
	"\rSoftwareImage\x120\n" +
	"\x04name\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x04name\x126\n" +
	"\aversion\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\aversion\x12@\n" +
	"\bmetadata\x18\x03 \x01(\v2$.arista.imagestatus.v1.ImageMetadataR\bmetadata\"\x9f\x02\n" +
	"\rImageMetadata\x126\n" +
	"\aversion\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\aversion\x126\n" +
	"\arelease\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\arelease\x124\n" +
	"\x06flavor\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x06flavor\x126\n" +
	"\avariant\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\avariant\x120\n" +
	"\x04arch\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x04arch\"\xef\x03\n" +
	"\tExtension\x120\n" +
	"\x04name\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x04name\x126\n" +
	"\aversion\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\aversion\x12C\n" +
	"\x0freboot_required\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\x0erebootRequired\x124\n" +
	"\apresent\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueR\apresent\x12K\n" +
	"\tinstalled\x18\x05 \x01(\x0e2-.arista.imagestatus.v1.ExtensionInstallStatusR\tinstalled\x12A\n" +
	"\rstatus_detail\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\fstatusDetail\x12;\n" +
	"\vis_embedded\x18\a \x01(\v2\x1a.google.protobuf.BoolValueR\n" +
	"isEmbedded\x120\n" +
	"\x04arch\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\x04arch\"F\n" +
	"\n" +
	"Extensions\x128\n" +
	"\x06values\x18\x01 \x03(\v2 .arista.imagestatus.v1.ExtensionR\x06values\"\xe0\x02\n" +
	"\x10ComplianceStatus\x12r\n" +
	"\x1esoftware_image_compliance_code\x18\x01 \x01(\x0e2-.arista.imagestatus.v1.SoftwareComplianceCodeR\x1bsoftwareImageComplianceCode\x12k\n" +
	"\x1aterminattr_compliance_code\x18\x02 \x01(\x0e2-.arista.imagestatus.v1.SoftwareComplianceCodeR\x18terminattrComplianceCode\x12k\n" +
	"\x1aextensions_compliance_code\x18\x03 \x01(\x0e2-.arista.imagestatus.v1.SoftwareComplianceCodeR\x18extensionsComplianceCode\"\xcd\x01\n" +
	"\x15ComplianceStatusBySup\x12P\n" +
	"\x06values\x18\x01 \x03(\v28.arista.imagestatus.v1.ComplianceStatusBySup.ValuesEntryR\x06values\x1ab\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12=\n" +
	"\x05value\x18\x02 \x01(\v2'.arista.imagestatus.v1.ComplianceStatusR\x05value:\x028\x01\"\xa3\x02\n" +
	"\x0eRebootRequired\x12_\n" +
	"\x1esoftware_image_reboot_required\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\x1bsoftwareImageRebootRequired\x12X\n" +
	"\x1aterminattr_reboot_required\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\x18terminattrRebootRequired\x12V\n" +
	"\x19extension_reboot_required\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\x17extensionRebootRequired\"\xea\x01\n" +
	"\x11SoftwareImageDiff\x121\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1d.arista.imagestatus.v1.DiffOpR\x04code\x122\n" +
	"\x01a\x18\x02 \x01(\v2$.arista.imagestatus.v1.SoftwareImageR\x01a\x122\n" +
	"\x01b\x18\x03 \x01(\v2$.arista.imagestatus.v1.SoftwareImageR\x01b\x12:\n" +
	"\ttext_code\x18\x04 \x01(\x0e2\x1d.arista.imagestatus.v1.DiffOpR\btextCode\"\xd2\x01\n" +
	"\x17SoftwareImageDiffsBySup\x12R\n" +
	"\x06values\x18\x01 \x03(\v2:.arista.imagestatus.v1.SoftwareImageDiffsBySup.ValuesEntryR\x06values\x1ac\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12>\n" +
	"\x05value\x18\x02 \x01(\v2(.arista.imagestatus.v1.SoftwareImageDiffR\x05value:\x028\x01\"\xde\x01\n" +
	"\rExtensionDiff\x121\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1d.arista.imagestatus.v1.DiffOpR\x04code\x12.\n" +
	"\x01a\x18\x02 \x01(\v2 .arista.imagestatus.v1.ExtensionR\x01a\x12.\n" +
	"\x01b\x18\x03 \x01(\v2 .arista.imagestatus.v1.ExtensionR\x01b\x12:\n" +
	"\ttext_code\x18\x04 \x01(\x0e2\x1d.arista.imagestatus.v1.DiffOpR\btextCode\"\xc8\x01\n" +
	"\x14TerminAttrDiffsBySup\x12O\n" +
	"\x06values\x18\x01 \x03(\v27.arista.imagestatus.v1.TerminAttrDiffsBySup.ValuesEntryR\x06values\x1a_\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.arista.imagestatus.v1.ExtensionDiffR\x05value:\x028\x01\"N\n" +
	"\x0eExtensionDiffs\x12<\n" +
	"\x06values\x18\x01 \x03(\v2$.arista.imagestatus.v1.ExtensionDiffR\x06values\"\xc7\x01\n" +
	"\x13ExtensionDiffsBySup\x12N\n" +
	"\x06values\x18\x01 \x03(\v26.arista.imagestatus.v1.ExtensionDiffsBySup.ValuesEntryR\x06values\x1a`\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.arista.imagestatus.v1.ExtensionDiffsR\x05value:\x028\x01\"\xde\a\n" +
	"\fImageSummary\x12.\n" +
	"\x03sku\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x03sku\x12U\n" +
	"\x19running_image_update_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x16runningImageUpdateTime\x12W\n" +
	"\x1adesigned_image_update_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x17designedImageUpdateTime\x125\n" +
	"\bdual_sup\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueR\adualSup\x12<\n" +
	"\vactive_slot\x18\x05 \x01(\v2\x1b.google.protobuf.Int32ValueR\n" +
	"activeSlot\x12>\n" +
	"\fstandby_slot\x18\x06 \x01(\v2\x1b.google.protobuf.Int32ValueR\vstandbySlot\x12^\n" +
	"\x13software_image_diff\x18\a \x01(\v2..arista.imagestatus.v1.SoftwareImageDiffsBySupR\x11softwareImageDiff\x12T\n" +
	"\x0fterminattr_diff\x18\b \x01(\v2+.arista.imagestatus.v1.TerminAttrDiffsBySupR\x0eterminattrDiff\x12S\n" +
	"\x0fextensions_diff\x18\t \x01(\v2*.arista.imagestatus.v1.ExtensionDiffsBySupR\x0eextensionsDiff\x12Z\n" +
	"\x11compliance_status\x18\n" +
	" \x01(\x0e2-.arista.imagestatus.v1.SoftwareComplianceCodeR\x10complianceStatus\x12L\n" +
	"\n" +
	"compliance\x18\v \x01(\v2,.arista.imagestatus.v1.ComplianceStatusBySupR\n" +
	"compliance\x12N\n" +
	"\x0freboot_required\x18\f \x01(\v2%.arista.imagestatus.v1.RebootRequiredR\x0erebootRequired\x124\n" +
	"\x06digest\x18\r \x01(\v2\x1c.google.protobuf.StringValueR\x06digest\"M\n" +
	"\n" +
	"SummaryKey\x129\n" +
	"\tdevice_id\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\bdeviceId:\x04\x80\x8e\x19\x01\"\xbc\x02\n" +
	"\aSummary\x123\n" +
	"\x03key\x18\x01 \x01(\v2!.arista.imagestatus.v1.SummaryKeyR\x03key\x12=\n" +
	"\asummary\x18\x02 \x01(\v2#.arista.imagestatus.v1.ImageSummaryR\asummary\x12:\n" +
	"\x06errors\x18\x03 \x01(\v2\".arista.imagestatus.v1.ImageErrorsR\x06errors\x12@\n" +
	"\bwarnings\x18\x04 \x01(\v2$.arista.imagestatus.v1.ImageWarningsR\bwarnings\x127\n" +
	"\x05infos\x18\x05 \x01(\v2!.arista.imagestatus.v1.ImageInfosR\x05infos:\x06\xfa\x8d\x19\x02ro\"\xb8\x01\n" +
	"\n" +
	"ImageError\x12.\n" +
	"\x03sku\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x03sku\x12?\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x0e2 .arista.imagestatus.v1.ErrorCodeR\terrorCode\x129\n" +
	"\terror_msg\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\berrorMsg\"H\n" +
	"\vImageErrors\x129\n" +
	"\x06values\x18\x01 \x03(\v2!.arista.imagestatus.v1.ImageErrorR\x06values\"\xc4\x01\n" +
	"\fImageWarning\x12.\n" +
	"\x03sku\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x03sku\x12E\n" +
	"\fwarning_code\x18\x02 \x01(\x0e2\".arista.imagestatus.v1.WarningCodeR\vwarningCode\x12=\n" +
	"\vwarning_msg\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"warningMsg\"L\n" +
	"\rImageWarnings\x12;\n" +
	"\x06values\x18\x01 \x03(\v2#.arista.imagestatus.v1.ImageWarningR\x06values\"\xb2\x01\n" +
	"\tImageInfo\x12.\n" +
	"\x03sku\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x03sku\x12<\n" +
	"\tinfo_code\x18\x02 \x01(\x0e2\x1f.arista.imagestatus.v1.InfoCodeR\binfoCode\x127\n" +
	"\binfo_msg\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\ainfoMsg\"F\n" +
	"\n" +
	"ImageInfos\x128\n" +
	"\x06values\x18\x01 \x03(\v2 .arista.imagestatus.v1.ImageInfoR\x06values*\xc4\x01\n" +
	"\x16ExtensionInstallStatus\x12(\n" +
	"$EXTENSION_INSTALL_STATUS_UNSPECIFIED\x10\x00\x12*\n" +
	"&EXTENSION_INSTALL_STATUS_NOT_INSTALLED\x10\x01\x12&\n" +
	"\"EXTENSION_INSTALL_STATUS_INSTALLED\x10\x02\x12,\n" +
	"(EXTENSION_INSTALL_STATUS_FORCE_INSTALLED\x10\x03*\x92\x01\n" +
	"\x16SoftwareComplianceCode\x12(\n" +
	"$SOFTWARE_COMPLIANCE_CODE_UNSPECIFIED\x10\x00\x12$\n" +
	" SOFTWARE_COMPLIANCE_CODE_IN_SYNC\x10\x01\x12(\n" +
	"$SOFTWARE_COMPLIANCE_CODE_OUT_OF_SYNC\x10\x02*k\n" +
	"\x06DiffOp\x12\x17\n" +
	"\x13DIFF_OP_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vDIFF_OP_NOP\x10\x01\x12\x0f\n" +
	"\vDIFF_OP_ADD\x10\x02\x12\x12\n" +
	"\x0eDIFF_OP_DELETE\x10\x03\x12\x12\n" +
	"\x0eDIFF_OP_CHANGE\x10\x04*\xd6\x06\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12)\n" +
	"!ERROR_CODE_SUPPORT_NOT_INTRODUCED\x10\x01\x1a\x02\b\x01\x12\"\n" +
	"\x1aERROR_CODE_SUPPORT_REMOVED\x10\x02\x1a\x02\b\x01\x12!\n" +
	"\x1dERROR_CODE_DEVICE_UNREACHABLE\x10\x03\x12 \n" +
	"\x1cERROR_CODE_VALIDATION_FAILED\x10\x04\x12-\n" +
	")ERROR_CODE_GET_PROPOSED_IMAGE_INFO_FAILED\x10\x05\x12G\n" +
	"?ERROR_CODE_GET_RUNNING_IMAGE_INFO_FROM_ACTIVE_SUPERVISOR_FAILED\x10\x06\x1a\x02\b\x01\x12E\n" +
	"=ERROR_CODE_GET_RUNNING_IMAGE_INFO_FROM_PEER_SUPERVISOR_FAILED\x10\a\x1a\x02\b\x01\x12/\n" +
	"+ERROR_CODE_EOS_TA_ARCHITECTURE_INCOMPATIBLE\x10\b\x12!\n" +
	"\x1dERROR_CODE_TA_CV_INCOMPATIBLE\x10\t\x12\"\n" +
	"\x1eERROR_CODE_EOS_CV_INCOMPATIBLE\x10\n" +
	"\x12)\n" +
	"%ERROR_CODE_EOS_SUPPORT_NOT_INTRODUCED\x10\v\x12\"\n" +
	"\x1eERROR_CODE_EOS_SUPPORT_REMOVED\x10\f\x12/\n" +
	"+ERROR_CODE_PHYSICAL_DEVICE_EOS_INCOMPATIBLE\x10\r\x12*\n" +
	"&ERROR_CODE_TA_EMBEDDEDEXT_INCOMPATIBLE\x10\x0e\x12*\n" +
	"&ERROR_CODE_DEVICE_EOS_2GB_INCOMPATIBLE\x10\x0f\x121\n" +
	"-ERROR_CODE_EOS_EXTENSION_VERSION_INCOMPATIBLE\x10\x10\x12\x1f\n" +
	"\x1bERROR_CODE_ARCH_UNSUPPORTED\x10\x11\x126\n" +
	"2ERROR_CODE_EOS_EXTENSION_ARCHITECTURE_INCOMPATIBLE\x10\x12*\xa7\x05\n" +
	"\vWarningCode\x12\x1c\n" +
	"\x18WARNING_CODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bWARNING_CODE_NOT_APPLICABLE\x10\x01\x12$\n" +
	" WARNING_CODE_SKUINFO_UNAVAILABLE\x10\x02\x12'\n" +
	"#WARNING_CODE_DEVICE_SKU_UNAVAILABLE\x10\x03\x12\x1c\n" +
	"\x18WARNING_CODE_SWI_UNKNOWN\x10\x04\x12$\n" +
	" WARNING_CODE_TA_EOS_INCOMPATIBLE\x10\x05\x12#\n" +
	"\x1fWARNING_CODE_TA_CV_INCOMPATIBLE\x10\x06\x12$\n" +
	" WARNING_CODE_EOS_CV_INCOMPATIBLE\x10\a\x12!\n" +
	"\x1dWARNING_CODE_EOS_ARCH_UNKNOWN\x10\b\x12,\n" +
	"(WARNING_CODE_TA_EMBEDDEDEXT_INCOMPATIBLE\x10\t\x12&\n" +
	"\x1eWARNING_CODE_ARCH_INCOMPATIBLE\x10\n" +
	"\x1a\x02\b\x01\x12,\n" +
	"(WARNING_CODE_EOS_END_OF_LIFE_DATE_PASSED\x10\v\x12'\n" +
	"#WARNING_CODE_SUPPORT_NOT_INTRODUCED\x10\f\x12 \n" +
	"\x1cWARNING_CODE_SUPPORT_REMOVED\x10\r\x127\n" +
	"3WARNING_CODE_RUNNING_TA_BELOW_MIN_SUPPORTED_VERSION\x10\x0e\x12'\n" +
	"#WARNING_CODE_TA_STUDIO_INCOMPATIBLE\x10\x0f\x12'\n" +
	"#WARNING_CODE_BUGALERTS_DATA_MISSING\x10\x10*x\n" +
	"\bInfoCode\x12\x19\n" +
	"\x15INFO_CODE_UNSPECIFIED\x10\x00\x12%\n" +
	"!INFO_CODE_NEWER_VERSION_AVAILABLE\x10\x01\x12*\n" +
	"&INFO_CODE_UNIVERSAL_IMAGE_ARCH_APPLIED\x10\x02*\x87\x01\n" +
	"\vImageSource\x12\x1c\n" +
	"\x18IMAGE_SOURCE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13IMAGE_SOURCE_STUDIO\x10\x01\x12%\n" +
	"!IMAGE_SOURCE_NETWORK_PROVISIONING\x10\x02\x12\x1a\n" +
	"\x16IMAGE_SOURCE_HIERARCHY\x10\x03B\xfe\x01\n" +
	"\x19com.arista.imagestatus.v1B\x10ImagestatusProtoP\x01ZYgithub.com/ioplane/terraform-provider-cvp/internal/pb/arista/imagestatus.v1;imagestatusv1\xa2\x02\x03AIX\xaa\x02\x15Arista.Imagestatus.V1\xca\x02\x15Arista\\Imagestatus\\V1\xe2\x02!Arista\\Imagestatus\\V1\\GPBMetadata\xea\x02\x17Arista::Imagestatus::V1b\x06proto3"

var (
	file_arista_imagestatus_v1_imagestatus_proto_rawDescOnce sync.Once
	file_arista_imagestatus_v1_imagestatus_proto_rawDescData []byte
)

func file_arista_imagestatus_v1_imagestatus_proto_rawDescGZIP() []byte {
	file_arista_imagestatus_v1_imagestatus_proto_rawDescOnce.Do(func() {
		file_arista_imagestatus_v1_imagestatus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arista_imagestatus_v1_imagestatus_proto_rawDesc), len(file_arista_imagestatus_v1_imagestatus_proto_rawDesc)))
	})
	return file_arista_imagestatus_v1_imagestatus_proto_rawDescData
}

var file_arista_imagestatus_v1_imagestatus_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_arista_imagestatus_v1_imagestatus_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_arista_imagestatus_v1_imagestatus_proto_goTypes = []any{
	(ExtensionInstallStatus)(0),     // 0: arista.imagestatus.v1.ExtensionInstallStatus
	(SoftwareComplianceCode)(0),     // 1: arista.imagestatus.v1.SoftwareComplianceCode
	(DiffOp)(0),                     // 2: arista.imagestatus.v1.DiffOp
	(ErrorCode)(0),                  // 3: arista.imagestatus.v1.ErrorCode
	(WarningCode)(0),                // 4: arista.imagestatus.v1.WarningCode
	(InfoCode)(0),                   // 5: arista.imagestatus.v1.InfoCode
	(ImageSource)(0),                // 6: arista.imagestatus.v1.ImageSource
	(*SoftwareImage)(nil),           // 7: arista.imagestatus.v1.SoftwareImage
	(*ImageMetadata)(nil),           // 8: arista.imagestatus.v1.ImageMetadata
	(*Extension)(nil),               // 9: arista.imagestatus.v1.Extension
	(*Extensions)(nil),              // 10: arista.imagestatus.v1.Extensions
	(*ComplianceStatus)(nil),        // 11: arista.imagestatus.v1.ComplianceStatus
	(*ComplianceStatusBySup)(nil),   // 12: arista.imagestatus.v1.ComplianceStatusBySup
	(*RebootRequired)(nil),          // 13: arista.imagestatus.v1.RebootRequired
	(*SoftwareImageDiff)(nil),       // 14: arista.imagestatus.v1.SoftwareImageDiff
	(*SoftwareImageDiffsBySup)(nil), // 15: arista.imagestatus.v1.SoftwareImageDiffsBySup
	(*ExtensionDiff)(nil),           // 16: arista.imagestatus.v1.ExtensionDiff
	(*TerminAttrDiffsBySup)(nil),    // 17: arista.imagestatus.v1.TerminAttrDiffsBySup
	(*ExtensionDiffs)(nil),          // 18: arista.imagestatus.v1.ExtensionDiffs
	(*ExtensionDiffsBySup)(nil),     // 19: arista.imagestatus.v1.ExtensionDiffsBySup
	(*ImageSummary)(nil),            // 20: arista.imagestatus.v1.ImageSummary
	(*SummaryKey)(nil),              // 21: arista.imagestatus.v1.SummaryKey
	(*Summary)(nil),                 // 22: arista.imagestatus.v1.Summary
	(*ImageError)(nil),              // 23: arista.imagestatus.v1.ImageError
	(*ImageErrors)(nil),             // 24: arista.imagestatus.v1.ImageErrors
	(*ImageWarning)(nil),            // 25: arista.imagestatus.v1.ImageWarning
	(*ImageWarnings)(nil),           // 26: arista.imagestatus.v1.ImageWarnings
	(*ImageInfo)(nil),               // 27: arista.imagestatus.v1.ImageInfo
	(*ImageInfos)(nil),              // 28: arista.imagestatus.v1.ImageInfos
	nil,                             // 29: arista.imagestatus.v1.ComplianceStatusBySup.ValuesEntry
	nil,                             // 30: arista.imagestatus.v1.SoftwareImageDiffsBySup.ValuesEntry
	nil,                             // 31: arista.imagestatus.v1.TerminAttrDiffsBySup.ValuesEntry
	nil,                             // 32: arista.imagestatus.v1.ExtensionDiffsBySup.ValuesEntry
	(*wrapperspb.StringValue)(nil),  // 33: google.protobuf.StringValue
	(*wrapperspb.BoolValue)(nil),    // 34: google.protobuf.BoolValue
	(*timestamppb.Timestamp)(nil),   // 35: google.protobuf.Timestamp
	(*wrapperspb.Int32Value)(nil),   // 36: google.protobuf.Int32Value
}
var file_arista_imagestatus_v1_imagestatus_proto_depIdxs = []int32{
	33, // 0: arista.imagestatus.v1.SoftwareImage.name:type_name -> google.protobuf.StringValue
	33, // 1: arista.imagestatus.v1.SoftwareImage.version:type_name -> google.protobuf.StringValue
	8,  // 2: arista.imagestatus.v1.SoftwareImage.metadata:type_name -> arista.imagestatus.v1.ImageMetadata
	33, // 3: arista.imagestatus.v1.ImageMetadata.version:type_name -> google.protobuf.StringValue
	33, // 4: arista.imagestatus.v1.ImageMetadata.release:type_name -> google.protobuf.StringValue
	33, // 5: arista.imagestatus.v1.ImageMetadata.flavor:type_name -> google.protobuf.StringValue
	33, // 6: arista.imagestatus.v1.ImageMetadata.variant:type_name -> google.protobuf.StringValue
	33, // 7: arista.imagestatus.v1.ImageMetadata.arch:type_name -> google.protobuf.StringValue
	33, // 8: arista.imagestatus.v1.Extension.name:type_name -> google.protobuf.StringValue
	33, // 9: arista.imagestatus.v1.Extension.version:type_name -> google.protobuf.StringValue
	34, // 10: arista.imagestatus.v1.Extension.reboot_required:type_name -> google.protobuf.BoolValue
	34, // 11: arista.imagestatus.v1.Extension.present:type_name -> google.protobuf.BoolValue
	0,  // 12: arista.imagestatus.v1.Extension.installed:type_name -> arista.imagestatus.v1.ExtensionInstallStatus
	33, // 13: arista.imagestatus.v1.Extension.status_detail:type_name -> google.protobuf.StringValue
	34, // 14: arista.imagestatus.v1.Extension.is_embedded:type_name -> google.protobuf.BoolValue
	33, // 15: arista.imagestatus.v1.Extension.arch:type_name -> google.protobuf.StringValue
	9,  // 16: arista.imagestatus.v1.Extensions.values:type_name -> arista.imagestatus.v1.Extension
	1,  // 17: arista.imagestatus.v1.ComplianceStatus.software_image_compliance_code:type_name -> arista.imagestatus.v1.SoftwareComplianceCode
	1,  // 18: arista.imagestatus.v1.ComplianceStatus.terminattr_compliance_code:type_name -> arista.imagestatus.v1.SoftwareComplianceCode
	1,  // 19: arista.imagestatus.v1.ComplianceStatus.extensions_compliance_code:type_name -> arista.imagestatus.v1.SoftwareComplianceCode
	29, // 20: arista.imagestatus.v1.ComplianceStatusBySup.values:type_name -> arista.imagestatus.v1.ComplianceStatusBySup.ValuesEntry
	34, // 21: arista.imagestatus.v1.RebootRequired.software_image_reboot_required:type_name -> google.protobuf.BoolValue
	34, // 22: arista.imagestatus.v1.RebootRequired.terminattr_reboot_required:type_name -> google.protobuf.BoolValue
	34, // 23: arista.imagestatus.v1.RebootRequired.extension_reboot_required:type_name -> google.protobuf.BoolValue
	2,  // 24: arista.imagestatus.v1.SoftwareImageDiff.code:type_name -> arista.imagestatus.v1.DiffOp
	7,  // 25: arista.imagestatus.v1.SoftwareImageDiff.a:type_name -> arista.imagestatus.v1.SoftwareImage
	7,  // 26: arista.imagestatus.v1.SoftwareImageDiff.b:type_name -> arista.imagestatus.v1.SoftwareImage
	2,  // 27: arista.imagestatus.v1.SoftwareImageDiff.text_code:type_name -> arista.imagestatus.v1.DiffOp
	30, // 28: arista.imagestatus.v1.SoftwareImageDiffsBySup.values:type_name -> arista.imagestatus.v1.SoftwareImageDiffsBySup.ValuesEntry
	2,  // 29: arista.imagestatus.v1.ExtensionDiff.code:type_name -> arista.imagestatus.v1.DiffOp
	9,  // 30: arista.imagestatus.v1.ExtensionDiff.a:type_name -> arista.imagestatus.v1.Extension
	9,  // 31: arista.imagestatus.v1.ExtensionDiff.b:type_name -> arista.imagestatus.v1.Extension
	2,  // 32: arista.imagestatus.v1.ExtensionDiff.text_code:type_name -> arista.imagestatus.v1.DiffOp
	31, // 33: arista.imagestatus.v1.TerminAttrDiffsBySup.values:type_name -> arista.imagestatus.v1.TerminAttrDiffsBySup.ValuesEntry
	16, // 34: arista.imagestatus.v1.ExtensionDiffs.values:type_name -> arista.imagestatus.v1.ExtensionDiff
	32, // 35: arista.imagestatus.v1.ExtensionDiffsBySup.values:type_name -> arista.imagestatus.v1.ExtensionDiffsBySup.ValuesEntry
	33, // 36: arista.imagestatus.v1.ImageSummary.sku:type_name -> google.protobuf.StringValue
	35, // 37: arista.imagestatus.v1.ImageSummary.running_image_update_time:type_name -> google.protobuf.Timestamp
	35, // 38: arista.imagestatus.v1.ImageSummary.designed_image_update_time:type_name -> google.protobuf.Timestamp
	34, // 39: arista.imagestatus.v1.ImageSummary.dual_sup:type_name -> google.protobuf.BoolValue
	36, // 40: arista.imagestatus.v1.ImageSummary.active_slot:type_name -> google.protobuf.Int32Value
	36, // 41: arista.imagestatus.v1.ImageSummary.standby_slot:type_name -> google.protobuf.Int32Value
	15, // 42: arista.imagestatus.v1.ImageSummary.software_image_diff:type_name -> arista.imagestatus.v1.SoftwareImageDiffsBySup
	17, // 43: arista.imagestatus.v1.ImageSummary.terminattr_diff:type_name -> arista.imagestatus.v1.TerminAttrDiffsBySup
	19, // 44: arista.imagestatus.v1.ImageSummary.extensions_diff:type_name -> arista.imagestatus.v1.ExtensionDiffsBySup
	1,  // 45: arista.imagestatus.v1.ImageSummary.compliance_status:type_name -> arista.imagestatus.v1.SoftwareComplianceCode
	12, // 46: arista.imagestatus.v1.ImageSummary.compliance:type_name -> arista.imagestatus.v1.ComplianceStatusBySup
	13, // 47: arista.imagestatus.v1.ImageSummary.reboot_required:type_name -> arista.imagestatus.v1.RebootRequired
	33, // 48: arista.imagestatus.v1.ImageSummary.digest:type_name -> google.protobuf.StringValue
	33, // 49: arista.imagestatus.v1.SummaryKey.device_id:type_name -> google.protobuf.StringValue
	21, // 50: arista.imagestatus.v1.Summary.key:type_name -> arista.imagestatus.v1.SummaryKey
	20, // 51: arista.imagestatus.v1.Summary.summary:type_name -> arista.imagestatus.v1.ImageSummary
	24, // 52: arista.imagestatus.v1.Summary.errors:type_name -> arista.imagestatus.v1.ImageErrors
	26, // 53: arista.imagestatus.v1.Summary.warnings:type_name -> arista.imagestatus.v1.ImageWarnings
	28, // 54: arista.imagestatus.v1.Summary.infos:type_name -> arista.imagestatus.v1.ImageInfos
	33, // 55: arista.imagestatus.v1.ImageError.sku:type_name -> google.protobuf.StringValue
	3,  // 56: arista.imagestatus.v1.ImageError.error_code:type_name -> arista.imagestatus.v1.ErrorCode
	33, // 57: arista.imagestatus.v1.ImageError.error_msg:type_name -> google.protobuf.StringValue
	23, // 58: arista.imagestatus.v1.ImageErrors.values:type_name -> arista.imagestatus.v1.ImageError
	33, // 59: arista.imagestatus.v1.ImageWarning.sku:type_name -> google.protobuf.StringValue
	4,  // 60: arista.imagestatus.v1.ImageWarning.warning_code:type_name -> arista.imagestatus.v1.WarningCode
	33, // 61: arista.imagestatus.v1.ImageWarning.warning_msg:type_name -> google.protobuf.StringValue
	25, // 62: arista.imagestatus.v1.ImageWarnings.values:type_name -> arista.imagestatus.v1.ImageWarning
	33, // 63: arista.imagestatus.v1.ImageInfo.sku:type_name -> google.protobuf.StringValue
	5,  // 64: arista.imagestatus.v1.ImageInfo.info_code:type_name -> arista.imagestatus.v1.InfoCode
	33, // 65: arista.imagestatus.v1.ImageInfo.info_msg:type_name -> google.protobuf.StringValue
	27, // 66: arista.imagestatus.v1.ImageInfos.values:type_name -> arista.imagestatus.v1.ImageInfo
	11, // 67: arista.imagestatus.v1.ComplianceStatusBySup.ValuesEntry.value:type_name -> arista.imagestatus.v1.ComplianceStatus
	14, // 68: arista.imagestatus.v1.SoftwareImageDiffsBySup.ValuesEntry.value:type_name -> arista.imagestatus.v1.SoftwareImageDiff
	16, // 69: arista.imagestatus.v1.TerminAttrDiffsBySup.ValuesEntry.value:type_name -> arista.imagestatus.v1.ExtensionDiff
	18, // 70: arista.imagestatus.v1.ExtensionDiffsBySup.ValuesEntry.value:type_name -> arista.imagestatus.v1.ExtensionDiffs
	71, // [71:71] is the sub-list for method output_type
	71, // [71:71] is the sub-list for method input_type
	71, // [71:71] is the sub-list for extension type_name
	71, // [71:71] is the sub-list for extension extendee
	0,  // [0:71] is the sub-list for field type_name
}

func init() { file_arista_imagestatus_v1_imagestatus_proto_init() }
func file_arista_imagestatus_v1_imagestatus_proto_init() {
	if File_arista_imagestatus_v1_imagestatus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arista_imagestatus_v1_imagestatus_proto_rawDesc), len(file_arista_imagestatus_v1_imagestatus_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_arista_imagestatus_v1_imagestatus_proto_goTypes,
		DependencyIndexes: file_arista_imagestatus_v1_imagestatus_proto_depIdxs,
		EnumInfos:         file_arista_imagestatus_v1_imagestatus_proto_enumTypes,
		MessageInfos:      file_arista_imagestatus_v1_imagestatus_proto_msgTypes,
	}.Build()
	File_arista_imagestatus_v1_imagestatus_proto = out.File
	file_arista_imagestatus_v1_imagestatus_proto_goTypes = nil
	file_arista_imagestatus_v1_imagestatus_proto_depIdxs = nil
}
